package sdk

import (
	"fmt"
	"go/format"
	"strings"
)

func RenderGoFile(packageName string, response GenerateResponse) ([]byte, error) {
	packageName = strings.TrimSpace(packageName)
	if packageName == "" {
		packageName = "generated"
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by RPL. DO NOT EDIT.\n")
	builder.WriteString("package ")
	builder.WriteString(packageName)
	builder.WriteString("\n\n")

	if len(response.Imports) > 0 {
		builder.WriteString("import (\n")
		for _, item := range response.Imports {
			builder.WriteString("\t")
			if alias := strings.TrimSpace(item.Alias); alias != "" {
				builder.WriteString(alias)
				builder.WriteString(" ")
			}
			builder.WriteString(fmt.Sprintf("%q", item.Path))
			builder.WriteString("\n")
		}
		builder.WriteString(")\n\n")
	}

	for i, block := range response.Blocks {
		builder.WriteString(strings.TrimSpace(block.Code))
		builder.WriteString("\n")
		if i != len(response.Blocks)-1 {
			builder.WriteString("\n")
		}
	}

	source := builder.String()
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated Go package %q: %w", packageName, err)
	}

	return formatted, nil
}
