package main

import (
	"fmt"
	"rpl/pkg/sdk"
	"strings"
)

func generateFFIPythonClient(plan *ffiPlan) string {
	prefix := plan.Prefix
	var out strings.Builder
	fmt.Fprintf(&out, `# Code generated by rpl:ffi. DO NOT EDIT.
from __future__ import annotations

import base64
import ctypes
import dataclasses
import datetime
import json
from dataclasses import dataclass
from typing import Any, Optional

ABI_VERSION = %d


class FFIView(ctypes.Structure):
    _fields_ = [("data", ctypes.POINTER(ctypes.c_uint8)), ("len", ctypes.c_size_t)]


class FFIBuffer(ctypes.Structure):
    _fields_ = [("data", ctypes.POINTER(ctypes.c_uint8)), ("len", ctypes.c_size_t)]


class FFIError(RuntimeError):
    def __init__(self, status: int, message: str) -> None:
        super().__init__(message or f"FFI call failed with status {status}")
        self.status = status


def _json_default(value: Any) -> Any:
    if dataclasses.is_dataclass(value):
        return {
            field.metadata.get("ffi_name", field.name): getattr(value, field.name)
            for field in dataclasses.fields(value)
        }
    if isinstance(value, (bytes, bytearray)):
        return {"$bytes": base64.b64encode(value).decode("ascii")}
    if isinstance(value, (datetime.datetime, datetime.date)):
        return value.isoformat()
    raise TypeError(f"cannot encode {type(value)!r} for FFI")


@dataclass
class %s:
`, plan.ABIVersion, plan.Model.Name)
	if len(plan.Fields) == 0 {
		out.WriteString("    pass\n")
	}
	for _, field := range plan.Fields {
		fmt.Fprintf(&out, "    %s: %s = dataclasses.field(metadata={\"ffi_name\": %q})\n", ffiPythonName(field.WireName), ffiPythonType(field.Type), field.WireName)
	}
	out.WriteString("\n\nclass Client:\n")
	fmt.Fprintf(&out, `    def __init__(self, library_path: str, server_handle: int) -> None:
        self._library = ctypes.CDLL(library_path)
        self._server = ctypes.c_void_p(server_handle)
        if not self._server:
            raise ValueError("server_handle must not be null")
        self._abi_version = self._library.%s_ffi_abi_version
        self._abi_version.argtypes = []
        self._abi_version.restype = ctypes.c_uint32
        if int(self._abi_version()) != ABI_VERSION:
            raise FFIError(1, "FFI ABI version mismatch")
        self._call = self._library.%s_ffi_server_call
        self._call.argtypes = [ctypes.c_void_p, FFIView, FFIView, ctypes.POINTER(FFIBuffer), ctypes.POINTER(FFIBuffer)]
        self._call.restype = ctypes.c_int32
        self._free = self._library.%s_ffi_buffer_free
        self._free.argtypes = [FFIBuffer]
        self._free.restype = None

    @classmethod
    def from_factory(cls, library_path: str, factory_symbol: str = "%s_ffi_server_default") -> "Client":
        library = ctypes.CDLL(library_path)
        factory = getattr(library, factory_symbol)
        factory.argtypes = []
        factory.restype = ctypes.c_void_p
        handle = factory()
        if not handle:
            raise FFIError(1, f"factory {factory_symbol!r} returned null")
        client = cls.__new__(cls)
        client._library = library
        client._server = ctypes.c_void_p(handle)
        client._abi_version = library.%s_ffi_abi_version
        client._abi_version.argtypes = []
        client._abi_version.restype = ctypes.c_uint32
        if int(client._abi_version()) != ABI_VERSION:
            raise FFIError(1, "FFI ABI version mismatch")
        client._call = library.%s_ffi_server_call
        client._call.argtypes = [ctypes.c_void_p, FFIView, FFIView, ctypes.POINTER(FFIBuffer), ctypes.POINTER(FFIBuffer)]
        client._call.restype = ctypes.c_int32
        client._free = library.%s_ffi_buffer_free
        client._free.argtypes = [FFIBuffer]
        client._free.restype = None
        return client

    @staticmethod
    def _view(value: bytes) -> tuple[FFIView, Any]:
        if not value:
            return FFIView(None, 0), None
        storage = (ctypes.c_uint8 * len(value)).from_buffer_copy(value)
        return FFIView(ctypes.cast(storage, ctypes.POINTER(ctypes.c_uint8)), len(value)), storage

    def _invoke(self, method: str, request: dict[str, Any]) -> Any:
        method_view, method_storage = self._view(method.encode("utf-8"))
        payload = json.dumps(request, default=_json_default, separators=(",", ":")).encode("utf-8")
        request_view, request_storage = self._view(payload)
        response = FFIBuffer()
        failure = FFIBuffer()
        status = int(self._call(self._server, method_view, request_view, ctypes.byref(response), ctypes.byref(failure)))
        _ = (method_storage, request_storage)
        try:
            if status != 0:
                message = ctypes.string_at(failure.data, failure.len).decode("utf-8", errors="replace") if failure.data else ""
                raise FFIError(status, message)
            raw = ctypes.string_at(response.data, response.len) if response.data else b"null"
            return json.loads(raw.decode("utf-8"))
        finally:
            self._free(response)
            self._free(failure)

`, prefix, prefix, prefix, prefix, prefix, prefix, prefix)
	for _, method := range plan.Methods {
		params := make([]string, 0, len(method.Params))
		requestItems := make([]string, 0, len(method.Params))
		for _, param := range method.Params {
			params = append(params, fmt.Sprintf("%s: %s", ffiPythonName(param.WireName), ffiPythonType(param.Type)))
			requestItems = append(requestItems, fmt.Sprintf("%q: %s", param.WireName, ffiPythonName(param.WireName)))
		}
		separator := ""
		if len(params) > 0 {
			separator = ", "
		}
		fmt.Fprintf(&out, "    def %s(self%s%s) -> Any:\n        return self._invoke(%q, {%s})\n\n", ffiPythonName(method.WireName), separator, strings.Join(params, ", "), method.WireName, strings.Join(requestItems, ", "))
	}
	return out.String()
}

func ffiPythonType(typeRef sdk.TypeRef) string {
	base := "Any"
	switch {
	case typeRef.IsTime():
		base = "datetime.datetime"
	case typeRef.IsString():
		base = "str"
	case typeRef.IsBool():
		base = "bool"
	case typeRef.IsInteger():
		base = "int"
	case typeRef.IsFloat():
		base = "float"
	}
	if typeRef.IsList {
		base = "list[" + base + "]"
	}
	if typeRef.Optional && !typeRef.IsList {
		base = "Optional[" + base + "]"
	}
	return base
}
