package main

import (
	"fmt"
	"rpl/pkg/sdk"
	"strings"
)

func generateFFIGoClient(plan *ffiPlan) string {
	var out strings.Builder
	out.WriteString(`// Code generated by rpl:ffi. DO NOT EDIT.
package ffigo

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

var ErrNilNative = errors.New("ffi native ABI is nil")

type NativeABI interface {
	Call(context.Context, string, []byte) ([]byte, error)
}

type Client struct {
	native NativeABI
}

func NewClient(native NativeABI) *Client {
	return &Client{native: native}
}

`)
	fmt.Fprintf(&out, "const ABIVersion uint32 = %d\n\n", plan.ABIVersion)
	fmt.Fprintf(&out, "type %s struct {\n", plan.Model.Name)
	for _, field := range plan.Fields {
		fmt.Fprintf(&out, "\t%s %s `json:%q`\n", field.Name, ffiGoType(field.Type), field.WireName)
	}
	out.WriteString("}\n\n")
	for _, method := range plan.Methods {
		requestName := method.ExportName + "Request"
		fmt.Fprintf(&out, "type %s struct {\n", requestName)
		for _, param := range method.Params {
			fmt.Fprintf(&out, "\t%s %s `json:%q`\n", ffiExportedName(param.Name), ffiGoType(param.Type), param.WireName)
		}
		out.WriteString("}\n\n")
		responseType := ""
		if len(method.Returns) > 1 {
			responseType = method.ExportName + "Response"
			fmt.Fprintf(&out, "type %s struct {\n", responseType)
			for _, result := range method.Returns {
				fmt.Fprintf(&out, "\t%s %s `json:%q`\n", ffiExportedName(result.Name), ffiGoType(result.Type), result.WireName)
			}
			out.WriteString("}\n\n")
		}

		signature := "error"
		if len(method.Returns) == 1 {
			responseType = ffiGoType(method.Returns[0].Type)
			signature = "(" + responseType + ", error)"
		} else if len(method.Returns) > 1 {
			signature = "(" + responseType + ", error)"
		}
		fmt.Fprintf(&out, "func (client *Client) %s(ctx context.Context, request %s) %s {\n", method.ExportName, requestName, signature)
		if len(method.Returns) == 0 {
			out.WriteString("\tif client == nil || client.native == nil { return ErrNilNative }\n")
		} else {
			fmt.Fprintf(&out, "\tvar result %s\n", responseType)
			out.WriteString("\tif client == nil || client.native == nil { return result, ErrNilNative }\n")
		}
		out.WriteString("\tpayload, err := json.Marshal(request)\n")
		if len(method.Returns) == 0 {
			out.WriteString("\tif err != nil { return err }\n")
			fmt.Fprintf(&out, "\t_, err = client.native.Call(ctx, %q, payload)\n\treturn err\n", method.WireName)
		} else {
			out.WriteString("\tif err != nil { return result, err }\n")
			fmt.Fprintf(&out, "\tbody, err := client.native.Call(ctx, %q, payload)\n", method.WireName)
			out.WriteString("\tif err != nil { return result, err }\n\tif err := json.Unmarshal(body, &result); err != nil { return result, err }\n\treturn result, nil\n")
		}
		out.WriteString("}\n\n")
	}
	out.WriteString("var _ = time.Time{}\n")
	return out.String()
}

func generateFFIGoCGO(plan *ffiPlan) string {
	prefix := plan.Prefix
	header := "../" + ffiCName(plan.Model.Name) + ".h"
	return fmt.Sprintf(`// Code generated by rpl:ffi. DO NOT EDIT.
//go:build rpl_ffi_cgo && cgo

package ffigo

/*
#cgo CFLAGS: -I${SRCDIR}/..
#cgo LDFLAGS: -l%s
#include <stdlib.h>
#include %q
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"
)

type CGONative struct {
	server *C.%s_ffi_server
}

func NewCGONative(handle uintptr) *CGONative {
	return &CGONative{server: (*C.%s_ffi_server)(unsafe.Pointer(handle))}
}

func (native *CGONative) Call(ctx context.Context, method string, payload []byte) ([]byte, error) {
	if native == nil || native.server == nil { return nil, errors.New("ffi server handle is nil") }
	if uint32(C.%s_ffi_abi_version()) != ABIVersion { return nil, errors.New("ffi ABI version mismatch") }
	if err := ctx.Err(); err != nil { return nil, err }
	methodData := C.CBytes([]byte(method))
	defer C.free(methodData)
	payloadData := C.CBytes(payload)
	defer C.free(payloadData)
	methodView := C.%s_ffi_view{data: (*C.uint8_t)(methodData), len: C.size_t(len(method))}
	payloadView := C.%s_ffi_view{data: (*C.uint8_t)(payloadData), len: C.size_t(len(payload))}
	var response C.%s_ffi_buffer
	var failure C.%s_ffi_buffer
	status := C.%s_ffi_server_call(native.server, methodView, payloadView, &response, &failure)
	defer C.%s_ffi_buffer_free(response)
	defer C.%s_ffi_buffer_free(failure)
	if status != 0 {
		return nil, errors.New(C.GoStringN((*C.char)(unsafe.Pointer(failure.data)), C.int(failure.len)))
	}
	if err := ctx.Err(); err != nil { return nil, err }
	return C.GoBytes(unsafe.Pointer(response.data), C.int(response.len)), nil
}
`, plan.Library, header, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix)
}

func generateFFIGoPureGo(plan *ffiPlan) string {
	prefix := plan.Prefix
	return fmt.Sprintf(`// Code generated by rpl:ffi. DO NOT EDIT.
//go:build rpl_ffi_purego && (darwin || linux || freebsd || netbsd || windows)

package ffigo

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"sync"
	"unsafe"

	"github.com/ebitengine/purego"
)

type pureGoLibrary interface {
	Lookup(string) (uintptr, error)
	Close() error
}

type pureGoBuffer struct {
	data *byte
	len  uintptr
}

type PureGoNative struct {
	mu          sync.Mutex
	library     pureGoLibrary
	server      uintptr
	ownsServer  bool
	closed      bool
	abiVersion  func() uint32
	serverCall  func(uintptr, *byte, uintptr, *byte, uintptr, *pureGoBuffer, *pureGoBuffer) int32
	bufferFree  func(*byte, uintptr)
	destroy     func(uintptr)
}

func DefaultPureGoLibraryPath() string {
	switch runtime.GOOS {
	case "darwin":
		return %q
	case "windows":
		return %q
	default:
		return %q
	}
}

func OpenPureGo(libraryPath string, serverHandle uintptr) (*PureGoNative, error) {
	if serverHandle == 0 { return nil, errors.New("ffi server handle is nil") }
	native, err := openPureGoNative(libraryPath)
	if err != nil { return nil, err }
	native.server = serverHandle
	return native, nil
}

func OpenPureGoFromFactory(libraryPath string, factorySymbol string) (*PureGoNative, error) {
	native, err := openPureGoNative(libraryPath)
	if err != nil { return nil, err }
	if factorySymbol == "" { factorySymbol = %q }
	var factory func() uintptr
	if err := bindPureGoFunction(native.library, &factory, factorySymbol); err != nil {
		_ = native.library.Close()
		return nil, err
	}
	native.server = factory()
	if native.server == 0 {
		_ = native.library.Close()
		return nil, errors.New("ffi server factory returned a nil handle")
	}
	native.ownsServer = true
	return native, nil
}

func openPureGoNative(libraryPath string) (*PureGoNative, error) {
	if libraryPath == "" { libraryPath = DefaultPureGoLibraryPath() }
	library, err := openPureGoLibrary(libraryPath)
	if err != nil { return nil, fmt.Errorf("open FFI library %%q: %%w", libraryPath, err) }
	native := &PureGoNative{library: library}
	bindings := []struct {
		target any
		name   string
	}{
		{&native.abiVersion, %q},
		{&native.serverCall, %q},
		{&native.bufferFree, %q},
		{&native.destroy, %q},
	}
	for _, binding := range bindings {
		if err := bindPureGoFunction(library, binding.target, binding.name); err != nil {
			_ = library.Close()
			return nil, err
		}
	}
	if native.abiVersion() != ABIVersion {
		_ = library.Close()
		return nil, fmt.Errorf("ffi ABI version mismatch: library=%%d client=%%d", native.abiVersion(), ABIVersion)
	}
	return native, nil
}

func bindPureGoFunction(library pureGoLibrary, target any, symbol string) (err error) {
	address, err := library.Lookup(symbol)
	if err != nil { return fmt.Errorf("resolve FFI symbol %%q: %%w", symbol, err) }
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("register FFI symbol %%q: %%v", symbol, recovered)
		}
	}()
	purego.RegisterFunc(target, address)
	return nil
}

func (native *PureGoNative) Call(ctx context.Context, method string, payload []byte) ([]byte, error) {
	if native == nil { return nil, ErrNilNative }
	if err := ctx.Err(); err != nil { return nil, err }
	native.mu.Lock()
	defer native.mu.Unlock()
	if native.closed || native.library == nil || native.server == 0 {
		return nil, errors.New("ffi purego native is closed")
	}
	methodBytes := []byte(method)
	var response pureGoBuffer
	var failure pureGoBuffer
	status := native.serverCall(
		native.server,
		pureGoData(methodBytes), uintptr(len(methodBytes)),
		pureGoData(payload), uintptr(len(payload)),
		&response, &failure,
	)
	runtime.KeepAlive(methodBytes)
	runtime.KeepAlive(payload)
	defer native.bufferFree(response.data, response.len)
	defer native.bufferFree(failure.data, failure.len)
	if status != 0 {
		message := string(pureGoBufferView(failure))
		if message == "" { message = fmt.Sprintf("ffi call failed with status %%d", status) }
		return nil, errors.New(message)
	}
	if err := ctx.Err(); err != nil { return nil, err }
	return append([]byte(nil), pureGoBufferView(response)...), nil
}

func (native *PureGoNative) Close() error {
	if native == nil { return nil }
	native.mu.Lock()
	defer native.mu.Unlock()
	if native.closed { return nil }
	native.closed = true
	if native.ownsServer && native.server != 0 { native.destroy(native.server) }
	native.server = 0
	if native.library == nil { return nil }
	err := native.library.Close()
	native.library = nil
	return err
}

func pureGoData(data []byte) *byte {
	if len(data) == 0 { return nil }
	return &data[0]
}

func pureGoBufferView(buffer pureGoBuffer) []byte {
	if buffer.data == nil || buffer.len == 0 { return nil }
	return unsafe.Slice(buffer.data, buffer.len)
}
`,
		"lib"+plan.Library+".dylib",
		plan.Library+".dll",
		"lib"+plan.Library+".so",
		prefix+"_ffi_server_default",
		prefix+"_ffi_abi_version",
		prefix+"_ffi_server_call_bytes",
		prefix+"_ffi_buffer_free_bytes",
		prefix+"_ffi_server_destroy",
	)
}

func generateFFIGoPureGoUnix() string {
	return `// Code generated by rpl:ffi. DO NOT EDIT.
//go:build rpl_ffi_purego && (darwin || linux || freebsd || netbsd)

package ffigo

import "github.com/ebitengine/purego"

type pureGoUnixLibrary struct {
	handle uintptr
}

func openPureGoLibrary(path string) (pureGoLibrary, error) {
	handle, err := purego.Dlopen(path, purego.RTLD_NOW|purego.RTLD_LOCAL)
	if err != nil { return nil, err }
	return &pureGoUnixLibrary{handle: handle}, nil
}

func (library *pureGoUnixLibrary) Lookup(name string) (uintptr, error) {
	return purego.Dlsym(library.handle, name)
}

func (library *pureGoUnixLibrary) Close() error {
	if library.handle == 0 { return nil }
	err := purego.Dlclose(library.handle)
	library.handle = 0
	return err
}
`
}

func generateFFIGoPureGoWindows() string {
	return `// Code generated by rpl:ffi. DO NOT EDIT.
//go:build rpl_ffi_purego && windows

package ffigo

import "syscall"

type pureGoWindowsLibrary struct {
	dll *syscall.DLL
}

func openPureGoLibrary(path string) (pureGoLibrary, error) {
	dll, err := syscall.LoadDLL(path)
	if err != nil { return nil, err }
	return &pureGoWindowsLibrary{dll: dll}, nil
}

func (library *pureGoWindowsLibrary) Lookup(name string) (uintptr, error) {
	procedure, err := library.dll.FindProc(name)
	if err != nil { return 0, err }
	return procedure.Addr(), nil
}

func (library *pureGoWindowsLibrary) Close() error {
	if library.dll == nil { return nil }
	err := library.dll.Release()
	library.dll = nil
	return err
}
`
}

func ffiGoType(typeRef sdk.TypeRef) string {
	base := "json.RawMessage"
	switch {
	case typeRef.IsTime():
		base = "time.Time"
	case typeRef.IsString():
		base = "string"
	case typeRef.IsBool():
		base = "bool"
	case typeRef.IsInteger():
		if strings.HasPrefix(typeRef.BaseName(), "u") || typeRef.BaseName() == "byte" {
			base = "uint64"
		} else {
			base = "int64"
		}
	case typeRef.IsFloat():
		base = "float64"
	}
	if typeRef.IsList {
		base = "[]" + base
	}
	if typeRef.Optional && !typeRef.IsList {
		base = "*" + base
	}
	return base
}
