package main

import (
	"fmt"
	"rpl/pkg/sdk"
	"strings"
)

func generateFFIHeader(plan *ffiPlan) string {
	prefix := plan.Prefix
	guard := strings.ToUpper(prefix) + "_FFI_H"
	var out strings.Builder
	fmt.Fprintf(&out, `/* Code generated by rpl:ffi. DO NOT EDIT. */
#ifndef %s
#define %s

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define %s_FFI_ABI_VERSION %d

typedef struct %s_ffi_view {
    const uint8_t *data;
    size_t len;
} %s_ffi_view;

typedef struct %s_ffi_buffer {
    uint8_t *data;
    size_t len;
} %s_ffi_buffer;

typedef enum %s_ffi_status {
    %s_FFI_OK = 0,
    %s_FFI_INVALID_ARGUMENT = 1,
    %s_FFI_UNKNOWN_METHOD = 2,
    %s_FFI_NOT_IMPLEMENTED = 3,
    %s_FFI_DECODE_ERROR = 4,
    %s_FFI_SERVICE_ERROR = 5,
    %s_FFI_PANIC = 6
} %s_ffi_status;

/* Complex values use canonical UTF-8 JSON in a view. time.Time is Unix ns. */
typedef struct %s_model {
`, guard, guard, strings.ToUpper(prefix), plan.ABIVersion,
		prefix, prefix, prefix, prefix,
		prefix, strings.ToUpper(prefix), strings.ToUpper(prefix), strings.ToUpper(prefix), strings.ToUpper(prefix), strings.ToUpper(prefix), strings.ToUpper(prefix), strings.ToUpper(prefix), prefix,
		prefix)
	if len(plan.Fields) == 0 {
		out.WriteString("    uint8_t _unused;\n")
	}
	for _, field := range plan.Fields {
		if field.Type.Optional {
			fmt.Fprintf(&out, "    uint8_t has_field_%s;\n", ffiCName(field.Name))
		}
		fmt.Fprintf(&out, "    %s field_%s; /* JSON name: %s */\n", ffiCType(prefix, field.Type), ffiCName(field.Name), field.WireName)
	}
	fmt.Fprintf(&out, `} %s_model;

typedef int32_t (*%s_ffi_method_fn)(
    void *context,
    %s_ffi_view request_json,
    %s_ffi_buffer *response_json,
    %s_ffi_buffer *error_message
);

typedef struct %s_ffi_service_vtable {
    uint32_t abi_version;
    void *context;
`, prefix, prefix, prefix, prefix, prefix, prefix)
	for _, method := range plan.Methods {
		fmt.Fprintf(&out, "    %s_ffi_method_fn method_%s; /* %s */\n", prefix, ffiCName(method.WireName), method.Name)
	}
	fmt.Fprintf(&out, `    void (*drop_context)(void *context);
} %s_ffi_service_vtable;

typedef struct %s_ffi_server %s_ffi_server;

uint32_t %s_ffi_abi_version(void);
void %s_ffi_server_destroy(%s_ffi_server *server);
int32_t %s_ffi_server_call(
    %s_ffi_server *server,
    %s_ffi_view method,
    %s_ffi_view request_json,
    %s_ffi_buffer *response_json,
    %s_ffi_buffer *error_message
);
void %s_ffi_buffer_free(%s_ffi_buffer buffer);
/* Pointer-only entry points for runtimes such as purego that avoid C structs by value. */
int32_t %s_ffi_server_call_bytes(
    %s_ffi_server *server,
    const uint8_t *method_data,
    size_t method_len,
    const uint8_t *request_data,
    size_t request_len,
    %s_ffi_buffer *response_json,
    %s_ffi_buffer *error_message
);
void %s_ffi_buffer_free_bytes(uint8_t *data, size_t len);

	`, prefix,
		prefix, prefix,
		prefix,
		prefix, prefix,
		prefix, prefix, prefix, prefix, prefix, prefix,
		prefix, prefix,
		prefix, prefix, prefix, prefix,
		prefix)
	if plan.Servers["c"] {
		fmt.Fprintf(&out, "%s_ffi_server *%s_ffi_server_create(%s_ffi_service_vtable service);\n", prefix, prefix, prefix)
		fmt.Fprintf(&out, "%s_ffi_buffer %s_ffi_buffer_copy(const uint8_t *data, size_t len);\n", prefix, prefix)
	}
	if plan.Clients["c"] {
		for _, method := range plan.Methods {
			upper := strings.ToUpper(prefix + "_FFI_METHOD_" + ffiCName(method.WireName))
			fmt.Fprintf(&out, "#define %s %q\n", upper, method.WireName)
			fmt.Fprintf(&out, "int32_t %s_ffi_client_%s(%s_ffi_server *server, %s_ffi_view request_json, %s_ffi_buffer *response_json, %s_ffi_buffer *error_message);\n", prefix, ffiCName(method.WireName), prefix, prefix, prefix, prefix)
		}
	}
	out.WriteString(`
#ifdef __cplusplus
}
#endif

#endif
`)
	return out.String()
}

func ffiCType(prefix string, typeRef sdk.TypeRef) string {
	if typeRef.IsList {
		return prefix + "_ffi_view"
	}
	if typeRef.IsTime() {
		return "int64_t"
	}
	base := typeRef.BaseName()
	switch base {
	case "string":
		return prefix + "_ffi_view"
	case "bool":
		return "uint8_t"
	case "int8":
		return "int8_t"
	case "int16":
		return "int16_t"
	case "int32":
		return "int32_t"
	case "uint8", "byte":
		return "uint8_t"
	case "uint16":
		return "uint16_t"
	case "uint32":
		return "uint32_t"
	case "uint", "uint64":
		return "uint64_t"
	case "float32":
		return "float"
	case "float64":
		return "double"
	case "int", "int64":
		return "int64_t"
	default:
		return prefix + "_ffi_view"
	}
}
