package main

import (
	"fmt"
	"rpl/pkg/sdk"
	"strings"
)

func generateFFIRustCargo(plan *ffiPlan) string {
	return fmt.Sprintf(`[package]
name = %q
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`, strings.ReplaceAll(plan.Library, ".", "_"))
}

func generateFFIRust(plan *ffiPlan) string {
	var out strings.Builder
	out.WriteString(`// Code generated by rpl:ffi. DO NOT EDIT.
#![allow(clippy::missing_safety_doc)]

use serde::{Deserialize, Serialize};
use std::ffi::c_void;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::ptr;
use std::slice;

`)
	fmt.Fprintf(&out, "pub const ABI_VERSION: u32 = %d;\n", plan.ABIVersion)
	out.WriteString(`pub const FFI_OK: i32 = 0;
pub const FFI_INVALID_ARGUMENT: i32 = 1;
pub const FFI_UNKNOWN_METHOD: i32 = 2;
pub const FFI_NOT_IMPLEMENTED: i32 = 3;
pub const FFI_DECODE_ERROR: i32 = 4;
pub const FFI_SERVICE_ERROR: i32 = 5;
pub const FFI_PANIC: i32 = 6;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FFIView {
    pub data: *const u8,
    pub len: usize,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FFIBuffer {
    pub data: *mut u8,
    pub len: usize,
}

impl Default for FFIBuffer {
    fn default() -> Self { Self { data: ptr::null_mut(), len: 0 } }
}

#[derive(Debug, Clone)]
pub struct FFIError {
    pub status: i32,
    pub message: String,
}

impl FFIError {
    pub fn new(status: i32, message: impl Into<String>) -> Self {
        Self { status, message: message.into() }
    }
}

impl std::fmt::Display for FFIError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for FFIError {}

`)
	fmt.Fprintf(&out, "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct %s {\n", plan.Model.Name)
	for _, field := range plan.Fields {
		fmt.Fprintf(&out, "    #[serde(rename = %q)]\n    pub %s: %s,\n", field.WireName, ffiRustName(field.WireName), ffiRustType(plan, field.Type))
	}
	out.WriteString("}\n\n")
	for _, method := range plan.Methods {
		fmt.Fprintf(&out, "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct %sRequest {\n", method.ExportName)
		for _, param := range method.Params {
			fmt.Fprintf(&out, "    #[serde(rename = %q)]\n    pub %s: %s,\n", param.WireName, ffiRustName(param.WireName), ffiRustType(plan, param.Type))
		}
		out.WriteString("}\n\n")
		if len(method.Returns) > 1 {
			fmt.Fprintf(&out, "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct %sResponse {\n", method.ExportName)
			for _, result := range method.Returns {
				fmt.Fprintf(&out, "    #[serde(rename = %q)]\n    pub %s: %s,\n", result.WireName, ffiRustName(result.WireName), ffiRustType(plan, result.Type))
			}
			out.WriteString("}\n\n")
		}
	}
	out.WriteString("pub trait FFIService {\n")
	for _, method := range plan.Methods {
		fmt.Fprintf(&out, "    fn %s(&mut self, request: %sRequest) -> Result<%s, FFIError>;\n", ffiRustName(method.WireName), method.ExportName, ffiRustResponseType(plan, method))
	}
	out.WriteString("}\n\n")

	if plan.Servers["rust"] {
		generateFFIRustServer(&out, plan)
	}
	if plan.Clients["rust"] {
		generateFFIRustClient(&out, plan)
	}
	return out.String()
}

func generateFFIRustServer(out *strings.Builder, plan *ffiPlan) {
	prefix := plan.Prefix
	out.WriteString(`struct ServerHandle {
    service: Box<dyn FFIService + Send>,
}

pub fn into_raw_server<S>(service: S) -> *mut c_void
where
    S: FFIService + Send + 'static,
{
    Box::into_raw(Box::new(ServerHandle { service: Box::new(service) })) as *mut c_void
}

fn owned_buffer(bytes: Vec<u8>) -> FFIBuffer {
    if bytes.is_empty() { return FFIBuffer::default(); }
    let mut boxed = bytes.into_boxed_slice();
    let result = FFIBuffer { data: boxed.as_mut_ptr(), len: boxed.len() };
    std::mem::forget(boxed);
    result
}

unsafe fn view_bytes<'a>(view: FFIView) -> Result<&'a [u8], FFIError> {
    if view.len == 0 { return Ok(&[]); }
    if view.data.is_null() { return Err(FFIError::new(FFI_INVALID_ARGUMENT, "FFI view data is null")); }
    Ok(slice::from_raw_parts(view.data, view.len))
}

fn dispatch(service: &mut dyn FFIService, method: &str, payload: &[u8]) -> Result<Vec<u8>, FFIError> {
    match method {
`)
	for _, method := range plan.Methods {
		fmt.Fprintf(out, "        %q => {\n", method.WireName)
		fmt.Fprintf(out, "            let request: %sRequest = serde_json::from_slice(payload).map_err(|error| FFIError::new(FFI_DECODE_ERROR, error.to_string()))?;\n", method.ExportName)
		fmt.Fprintf(out, "            let response = service.%s(request)?;\n", ffiRustName(method.WireName))
		out.WriteString("            serde_json::to_vec(&response).map_err(|error| FFIError::new(FFI_SERVICE_ERROR, error.to_string()))\n        }\n")
	}
	out.WriteString(`        _ => Err(FFIError::new(FFI_UNKNOWN_METHOD, "unknown FFI method")),
    }
}

`)
	fmt.Fprintf(out, `#[export_name = %q]
pub extern "C" fn exported_ffi_abi_version() -> u32 { ABI_VERSION }

#[export_name = %q]
pub unsafe extern "C" fn exported_ffi_server_destroy(server: *mut c_void) {
    if !server.is_null() { drop(Box::from_raw(server as *mut ServerHandle)); }
}

#[export_name = %q]
pub unsafe extern "C" fn exported_ffi_buffer_free(buffer: FFIBuffer) {
    if !buffer.data.is_null() {
        let slice = ptr::slice_from_raw_parts_mut(buffer.data, buffer.len);
        drop(Box::from_raw(slice));
    }
}

#[export_name = %q]
pub unsafe extern "C" fn exported_ffi_server_call(
    server: *mut c_void,
    method: FFIView,
    request_json: FFIView,
    response_json: *mut FFIBuffer,
    error_message: *mut FFIBuffer,
) -> i32 {
    if response_json.is_null() || error_message.is_null() {
        return FFI_INVALID_ARGUMENT;
    }
    *response_json = FFIBuffer::default();
    *error_message = FFIBuffer::default();
    if server.is_null() {
        *error_message = owned_buffer(b"FFI server handle is null".to_vec());
        return FFI_INVALID_ARGUMENT;
    }
    let operation = catch_unwind(AssertUnwindSafe(|| -> Result<Vec<u8>, FFIError> {
        let method = std::str::from_utf8(view_bytes(method)?).map_err(|error| FFIError::new(FFI_DECODE_ERROR, error.to_string()))?;
        let payload = view_bytes(request_json)?;
        dispatch(&mut *(*(server as *mut ServerHandle)).service, method, payload)
    }));
    match operation {
        Ok(Ok(body)) => { *response_json = owned_buffer(body); FFI_OK }
        Ok(Err(error)) => { *error_message = owned_buffer(error.message.into_bytes()); error.status }
        Err(_) => { *error_message = owned_buffer(b"panic crossed the FFI service boundary".to_vec()); FFI_PANIC }
    }
}

#[export_name = %q]
pub unsafe extern "C" fn exported_ffi_server_call_bytes(
    server: *mut c_void,
    method_data: *const u8,
    method_len: usize,
    request_data: *const u8,
    request_len: usize,
    response_json: *mut FFIBuffer,
    error_message: *mut FFIBuffer,
) -> i32 {
    exported_ffi_server_call(
        server,
        FFIView { data: method_data, len: method_len },
        FFIView { data: request_data, len: request_len },
        response_json,
        error_message,
    )
}

#[export_name = %q]
pub unsafe extern "C" fn exported_ffi_buffer_free_bytes(data: *mut u8, len: usize) {
    exported_ffi_buffer_free(FFIBuffer { data, len });
}

`, prefix+"_ffi_abi_version", prefix+"_ffi_server_destroy", prefix+"_ffi_buffer_free", prefix+"_ffi_server_call", prefix+"_ffi_server_call_bytes", prefix+"_ffi_buffer_free_bytes")
}

func generateFFIRustClient(out *strings.Builder, plan *ffiPlan) {
	prefix := plan.Prefix
	callName := "exported_ffi_server_call"
	freeName := "exported_ffi_buffer_free"
	abiName := "exported_ffi_abi_version"
	if !plan.Servers["rust"] {
		fmt.Fprintf(out, `#[link(name = %q)]
extern "C" {
    #[link_name = %q]
    fn external_ffi_abi_version() -> u32;
    #[link_name = %q]
    fn external_ffi_server_call(server: *mut c_void, method: FFIView, request_json: FFIView, response_json: *mut FFIBuffer, error_message: *mut FFIBuffer) -> i32;
    #[link_name = %q]
    fn external_ffi_buffer_free(buffer: FFIBuffer);
}

`, plan.Library, prefix+"_ffi_abi_version", prefix+"_ffi_server_call", prefix+"_ffi_buffer_free")
		callName = "external_ffi_server_call"
		freeName = "external_ffi_buffer_free"
		abiName = "external_ffi_abi_version"
	}
	out.WriteString(`pub struct Client {
    server: *mut c_void,
}

impl Client {
    pub unsafe fn from_raw(server: *mut c_void) -> Result<Self, FFIError> {
        if server.is_null() { return Err(FFIError::new(FFI_INVALID_ARGUMENT, "FFI server handle is null")); }
`)
	fmt.Fprintf(out, "        if %s() != ABI_VERSION { return Err(FFIError::new(FFI_INVALID_ARGUMENT, \"FFI ABI version mismatch\")); }\n", abiName)
	out.WriteString(`
        Ok(Self { server })
    }

    fn call<Req, Resp>(&mut self, method: &str, request: &Req) -> Result<Resp, FFIError>
    where
        Req: Serialize,
        Resp: for<'de> Deserialize<'de>,
    {
        let request = serde_json::to_vec(request).map_err(|error| FFIError::new(FFI_DECODE_ERROR, error.to_string()))?;
        let method_view = FFIView { data: method.as_ptr(), len: method.len() };
        let request_view = FFIView { data: request.as_ptr(), len: request.len() };
        let mut response = FFIBuffer::default();
        let mut failure = FFIBuffer::default();
`)
	fmt.Fprintf(out, "        let status = unsafe { %s(self.server, method_view, request_view, &mut response, &mut failure) };\n", callName)
	out.WriteString("        let response_bytes = unsafe { if response.data.is_null() { &[][..] } else { slice::from_raw_parts(response.data, response.len) } }.to_vec();\n")
	out.WriteString("        let failure_bytes = unsafe { if failure.data.is_null() { &[][..] } else { slice::from_raw_parts(failure.data, failure.len) } }.to_vec();\n")
	fmt.Fprintf(out, "        unsafe { %s(response); %s(failure); }\n", freeName, freeName)
	out.WriteString(`        if status != FFI_OK {
            return Err(FFIError::new(status, String::from_utf8_lossy(&failure_bytes).into_owned()));
        }
        serde_json::from_slice(&response_bytes).map_err(|error| FFIError::new(FFI_DECODE_ERROR, error.to_string()))
    }

`)
	for _, method := range plan.Methods {
		fmt.Fprintf(out, "    pub fn %s(&mut self, request: &%sRequest) -> Result<%s, FFIError> {\n        self.call(%q, request)\n    }\n\n", ffiRustName(method.WireName), method.ExportName, ffiRustResponseType(plan, method), method.WireName)
	}
	out.WriteString("}\n\n")
}

func ffiRustResponseType(plan *ffiPlan, method ffiMethod) string {
	switch len(method.Returns) {
	case 0:
		return "()"
	case 1:
		return ffiRustType(plan, method.Returns[0].Type)
	default:
		return method.ExportName + "Response"
	}
}

func ffiRustType(plan *ffiPlan, typeRef sdk.TypeRef) string {
	base := "serde_json::Value"
	switch {
	case typeRef.Name == plan.Model.Name:
		base = plan.Model.Name
	case typeRef.IsTime():
		base = "String"
	case typeRef.IsString():
		base = "String"
	case typeRef.IsBool():
		base = "bool"
	case typeRef.IsInteger():
		if strings.HasPrefix(typeRef.BaseName(), "u") || typeRef.BaseName() == "byte" {
			base = "u64"
		} else {
			base = "i64"
		}
	case typeRef.IsFloat():
		base = "f64"
	}
	if typeRef.IsList {
		base = "Vec<" + base + ">"
	}
	if typeRef.Optional && !typeRef.IsList {
		base = "Option<" + base + ">"
	}
	return base
}
