package main

import (
	"fmt"
	"strings"
)

func generateFFICServer(plan *ffiPlan) string {
	prefix := plan.Prefix
	header := "../" + ffiCName(plan.Model.Name) + ".h"
	var out strings.Builder
	fmt.Fprintf(&out, `/* Code generated by rpl:ffi. DO NOT EDIT. */
#include %q

#include <stdlib.h>
#include <string.h>

struct %s_ffi_server {
    %s_ffi_service_vtable service;
};

static int %s_ffi_view_equals(%s_ffi_view value, const char *text) {
    size_t len = strlen(text);
    return value.len == len && (len == 0 || (value.data != NULL && memcmp(value.data, text, len) == 0));
}

%s_ffi_buffer %s_ffi_buffer_copy(const uint8_t *data, size_t len) {
    %s_ffi_buffer result = {0};
    if (len == 0) return result;
    if (data == NULL) return result;
    result.data = (uint8_t *)malloc(len);
    if (result.data == NULL) return result;
    memcpy(result.data, data, len);
    result.len = len;
    return result;
}

void %s_ffi_buffer_free(%s_ffi_buffer buffer) {
    free(buffer.data);
}

static int32_t %s_ffi_fail(%s_ffi_buffer *error_message, int32_t status, const char *message) {
    if (error_message != NULL) {
        *error_message = %s_ffi_buffer_copy((const uint8_t *)message, strlen(message));
    }
    return status;
}

uint32_t %s_ffi_abi_version(void) {
    return %d;
}

%s_ffi_server *%s_ffi_server_create(%s_ffi_service_vtable service) {
    if (service.abi_version != %d) return NULL;
    %s_ffi_server *server = (%s_ffi_server *)calloc(1, sizeof(*server));
    if (server == NULL) return NULL;
    server->service = service;
    return server;
}

void %s_ffi_server_destroy(%s_ffi_server *server) {
    if (server == NULL) return;
    if (server->service.drop_context != NULL) server->service.drop_context(server->service.context);
    free(server);
}

int32_t %s_ffi_server_call(
    %s_ffi_server *server,
    %s_ffi_view method,
    %s_ffi_view request_json,
    %s_ffi_buffer *response_json,
    %s_ffi_buffer *error_message
) {
    if (response_json != NULL) *response_json = (%s_ffi_buffer){0};
    if (error_message != NULL) *error_message = (%s_ffi_buffer){0};
    if (server == NULL || response_json == NULL || error_message == NULL) {
        return %s_ffi_fail(error_message, %s_FFI_INVALID_ARGUMENT, "invalid FFI call arguments");
    }
`, header, prefix, prefix, prefix, prefix,
		prefix, prefix, prefix,
		prefix, prefix,
		prefix, prefix, prefix,
		prefix, plan.ABIVersion,
		prefix, prefix, prefix, plan.ABIVersion, prefix, prefix,
		prefix, prefix,
		prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, strings.ToUpper(prefix))
	for _, method := range plan.Methods {
		name := ffiCName(method.WireName)
		fmt.Fprintf(&out, `    if (%s_ffi_view_equals(method, %q)) {
        if (server->service.method_%s == NULL) {
            return %s_ffi_fail(error_message, %s_FFI_NOT_IMPLEMENTED, "FFI method callback is not installed");
        }
        return server->service.method_%s(server->service.context, request_json, response_json, error_message);
    }
`, prefix, method.WireName, name, prefix, strings.ToUpper(prefix), name)
	}
	fmt.Fprintf(&out, `    return %s_ffi_fail(error_message, %s_FFI_UNKNOWN_METHOD, "unknown FFI method");
}

int32_t %s_ffi_server_call_bytes(
    %s_ffi_server *server,
    const uint8_t *method_data,
    size_t method_len,
    const uint8_t *request_data,
    size_t request_len,
    %s_ffi_buffer *response_json,
    %s_ffi_buffer *error_message
) {
    %s_ffi_view method = {method_data, method_len};
    %s_ffi_view request = {request_data, request_len};
    return %s_ffi_server_call(server, method, request, response_json, error_message);
}

void %s_ffi_buffer_free_bytes(uint8_t *data, size_t len) {
    %s_ffi_buffer buffer = {data, len};
    %s_ffi_buffer_free(buffer);
}
`, prefix, strings.ToUpper(prefix),
		prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix)
	return out.String()
}

func generateFFICClient(plan *ffiPlan) string {
	prefix := plan.Prefix
	header := "../" + ffiCName(plan.Model.Name) + ".h"
	var out strings.Builder
	fmt.Fprintf(&out, "/* Code generated by rpl:ffi. DO NOT EDIT. */\n#include %q\n\n#include <string.h>\n\n", header)
	for _, method := range plan.Methods {
		name := ffiCName(method.WireName)
		fmt.Fprintf(&out, `int32_t %s_ffi_client_%s(
    %s_ffi_server *server,
    %s_ffi_view request_json,
    %s_ffi_buffer *response_json,
    %s_ffi_buffer *error_message
) {
    static const char method[] = %q;
    if (%s_ffi_abi_version() != %s_FFI_ABI_VERSION) return %s_FFI_INVALID_ARGUMENT;
    %s_ffi_view method_view = {(const uint8_t *)method, sizeof(method) - 1};
    return %s_ffi_server_call(server, method_view, request_json, response_json, error_message);
}

`, prefix, name, prefix, prefix, prefix, prefix, method.WireName, prefix, strings.ToUpper(prefix), strings.ToUpper(prefix), prefix, prefix)
	}
	return out.String()
}
