// Code generated by RPL. DO NOT EDIT.
package grpc

import (
	"context"
	"fmt"
	"google.golang.org/grpc"
	modelpkg "m/src/user"
)

type userGRPCClient struct {
	client UserServiceClient
}

// NewUserGRPCClient создает typed gRPC клиент для сервиса модели User.
func NewUserGRPCClient(conn grpc.ClientConnInterface) UserService {
	return WrapUserGRPCClient(NewUserServiceClient(conn))
}

// WrapUserGRPCClient оборачивает protobuf-клиент в сервисный API модели User.
func WrapUserGRPCClient(client UserServiceClient) UserService {
	return &userGRPCClient{client: client}
}

var _ UserService = (*userGRPCClient)(nil)

// Put вызывает удаленный gRPC метод Put для модели User.
func (client *userGRPCClient) Put(ctx context.Context, user modelpkg.User) (modelpkg.User, error) {
	if client == nil || client.client == nil {
		return modelpkg.User{}, fmt.Errorf("grpc client is nil")
	}
	response, err := client.client.Put(ctx, ToMessage(user))
	if err != nil {
		return modelpkg.User{}, err
	}
	return FromMessage(response)
}

// GetByID вызывает удаленный gRPC метод GetByID для модели User.
func (client *userGRPCClient) GetByID(ctx context.Context, id int) (modelpkg.User, error) {
	if client == nil || client.client == nil {
		return modelpkg.User{}, fmt.Errorf("grpc client is nil")
	}
	request := &UserGetByIDRequest{}
	request.Id = int64(id)
	response, err := client.client.GetByID(ctx, request)
	if err != nil {
		return modelpkg.User{}, err
	}
	return FromMessage(response)
}

// Delete вызывает удаленный gRPC метод Delete для модели User.
func (client *userGRPCClient) Delete(ctx context.Context, id int) error {
	if client == nil || client.client == nil {
		return fmt.Errorf("grpc client is nil")
	}
	request := &UserDeleteRequest{}
	request.Id = int64(id)
	_, err := client.client.Delete(ctx, request)
	if err != nil {
		return err
	}
	return nil
}

// List вызывает удаленный gRPC метод List для модели User.
func (client *userGRPCClient) List(ctx context.Context) ([]modelpkg.User, error) {
	if client == nil || client.client == nil {
		return nil, fmt.Errorf("grpc client is nil")
	}
	response, err := client.client.List(ctx, &UserListRequest{})
	if err != nil {
		return nil, err
	}
	if response == nil {
		response = &UserListResponse{}
	}
	items := make([]modelpkg.User, 0, len(response.Items))
	for _, item := range response.Items {
		value, err := FromMessage(item)
		if err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	return items, nil
}

// String вызывает удаленный gRPC метод String и возвращает обычные Go-значения.
func (client *userGRPCClient) String(ctx context.Context) (string, error) {
	if client == nil || client.client == nil {
		return "", fmt.Errorf("grpc client is nil")
	}
	request := &UserStringRequest{}
	response, err := client.client.String(ctx, request)
	if err != nil {
		return "", err
	}
	if response == nil {
		response = &UserStringResponse{}
	}
	result := response.Result
	return result, nil
}
