// Code generated by RPL. DO NOT EDIT.
package grpc

import (
	modelpkg "m/src/user"
)

// ToMessage преобразует модель User в protobuf-сообщение.
func ToMessage(model modelpkg.User) *UserMessage {
	message := &UserMessage{}
	message.Id = int64(model.Id)
	message.Name = model.Name
	message.Phone = model.Phone
	return message
}

// FromMessage восстанавливает модель User из protobuf-сообщения.
func FromMessage(message *UserMessage) (modelpkg.User, error) {
	model := modelpkg.User{}
	if message == nil {
		return model, nil
	}
	model.Id = int(message.Id)
	model.Name = message.Name
	model.Phone = message.Phone
	return model, nil
}
