// Code generated by RPL. DO NOT EDIT.
package grpc

import (
	"context"
	"fmt"
	"google.golang.org/grpc"
	modelpkg "m/src/user"
)

type UserService interface {
	Put(ctx context.Context, user modelpkg.User) (modelpkg.User, error)
	GetByID(ctx context.Context, id int) (modelpkg.User, error)
	Delete(ctx context.Context, id int) error
	List(ctx context.Context) ([]modelpkg.User, error)
	String(ctx context.Context) (string, error)
}

type UserGRPCServer struct {
	UnimplementedUserServiceServer
	Service UserService
}

// NewUserGRPCServer создает gRPC server adapter для сервиса модели User.
func NewUserGRPCServer(service UserService) *UserGRPCServer {
	return &UserGRPCServer{Service: service}
}

// RegisterUserGRPC регистрирует gRPC сервис модели User в переданном registrar.
func RegisterUserGRPC(registrar grpc.ServiceRegistrar, service UserService) {
	RegisterUserServiceServer(registrar, NewUserGRPCServer(service))
}

var _ UserServiceServer = (*UserGRPCServer)(nil)

// Put проксирует gRPC вызов Put к сервису модели User.
func (server *UserGRPCServer) Put(ctx context.Context, request *UserMessage) (*UserMessage, error) {
	if server == nil || server.Service == nil {
		return nil, fmt.Errorf("grpc service is nil")
	}
	user, err := FromMessage(request)
	if err != nil {
		return nil, err
	}
	result, err := server.Service.Put(ctx, user)
	if err != nil {
		return nil, err
	}
	return ToMessage(result), nil
}

// GetByID проксирует gRPC вызов GetByID к сервису модели User.
func (server *UserGRPCServer) GetByID(ctx context.Context, request *UserGetByIDRequest) (*UserMessage, error) {
	if server == nil || server.Service == nil {
		return nil, fmt.Errorf("grpc service is nil")
	}
	if request == nil {
		request = &UserGetByIDRequest{}
	}
	id := int(request.Id)
	result, err := server.Service.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return ToMessage(result), nil
}

// Delete проксирует gRPC вызов Delete к сервису модели User.
func (server *UserGRPCServer) Delete(ctx context.Context, request *UserDeleteRequest) (*UserDeleteResponse, error) {
	if server == nil || server.Service == nil {
		return nil, fmt.Errorf("grpc service is nil")
	}
	if request == nil {
		request = &UserDeleteRequest{}
	}
	id := int(request.Id)
	if err := server.Service.Delete(ctx, id); err != nil {
		return nil, err
	}
	return &UserDeleteResponse{}, nil
}

// List проксирует gRPC вызов List к сервису модели User.
func (server *UserGRPCServer) List(ctx context.Context, request *UserListRequest) (*UserListResponse, error) {
	_ = request
	if server == nil || server.Service == nil {
		return nil, fmt.Errorf("grpc service is nil")
	}
	items, err := server.Service.List(ctx)
	if err != nil {
		return nil, err
	}
	response := &UserListResponse{}
	if len(items) > 0 {
		response.Items = make([]*UserMessage, 0, len(items))
		for _, item := range items {
			response.Items = append(response.Items, ToMessage(item))
		}
	}
	return response, nil
}

// String проксирует gRPC вызов String к сервису модели User.
func (server *UserGRPCServer) String(ctx context.Context, request *UserStringRequest) (*UserStringResponse, error) {
	if server == nil || server.Service == nil {
		return nil, fmt.Errorf("grpc service is nil")
	}
	if request == nil {
		request = &UserStringRequest{}
	}
	result, err := server.Service.String(ctx)
	if err != nil {
		return nil, err
	}
	response := &UserStringResponse{}
	response.Result = result
	return response, nil
}
