// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-16T22:05:11+03:00
// RPL version: beta
// Author: <Author name>
package user

import (
	"sync"
)

// User описывает сгенерированную модель данных.
type User struct {
	Id    int
	Name  string
	Phone string
}

// UserMethods описывает реализацию model methods для User, объявленных в RPL-схеме.
type UserMethods interface {
	String(model *User) string
}

var (
	userMethodsMu   sync.RWMutex
	userMethodsImpl UserMethods
)

// SetUserMethods регистрирует реализацию методов модели User.
func SetUserMethods(methods UserMethods) {
	userMethodsMu.Lock()
	defer userMethodsMu.Unlock()
	userMethodsImpl = methods
}

func userMethods() UserMethods {
	userMethodsMu.RLock()
	defer userMethodsMu.RUnlock()
	return userMethodsImpl
}

// String вызывает зарегистрированную реализацию метода String для модели User.
func (model *User) String() string {
	methods := userMethods()
	if methods == nil {
		panic("UserMethods is not configured; call SetUserMethods")
	}
	return methods.String(model)
}
