// Code generated by RPL. DO NOT EDIT.
package user

// UserStdMethodMeta описывает метод поля в std-метаданных.
type UserStdMethodMeta struct {
	Name    string
	Params  []string
	Returns []string
	Inside  bool
}

// UserStdFieldMeta описывает поле модели и его стандартные метаданные.
type UserStdFieldMeta struct {
	Name      string
	Type      string
	Kind      string
	Optional  bool
	Repeated  bool
	Group     string
	Model     string
	External  bool
	IgnoredBy []string
	Methods   []UserStdMethodMeta
}

// StdComment возвращает комментарий модели User из attr `@comment`.
func (model User) StdComment() string {
	return "MongoDB-backed user storage with generated collection, indexes, BSON converters, and CRUD helpers."
}

// StdGroup возвращает группу модели User, если она задана.
func (model User) StdGroup() string {
	return ""
}

// StdFields возвращает полное std-описание полей модели User.
func (model User) StdFields() []UserStdFieldMeta {
	return []UserStdFieldMeta{
		UserStdFieldMeta{
			Name:      "ID",
			Type:      "string",
			Kind:      "string",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "Email",
			Type:      "string",
			Kind:      "string",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "Username",
			Type:      "string",
			Kind:      "string",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "Status",
			Type:      "string",
			Kind:      "string",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "Tags",
			Type:      "[]string",
			Kind:      "list",
			Optional:  false,
			Repeated:  true,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "CreatedAt",
			Type:      "time.Time",
			Kind:      "time",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "UpdatedAt",
			Type:      "time.Time",
			Kind:      "time",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: nil,
			Methods:   nil,
		},
		UserStdFieldMeta{
			Name:      "CacheKey",
			Type:      "string",
			Kind:      "string",
			Optional:  false,
			Repeated:  false,
			Group:     "",
			Model:     "",
			External:  false,
			IgnoredBy: []string{"mongodb"},
			Methods:   nil,
		},
	}
}

// StdField ищет std-метаданные конкретного поля модели User по имени.
func (model User) StdField(name string) (UserStdFieldMeta, bool) {
	for _, field := range model.StdFields() {
		if field.Name == name {
			return field, true
		}
	}

	return UserStdFieldMeta{}, false
}
