// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-16T22:19:01+03:00
// RPL version: beta
// Author: <Author name>
package user

import (
	"time"
)

// MongoDB-backed user storage with generated collection, indexes, BSON converters, and CRUD helpers.
type User struct {
	ID        string
	Email     string
	Username  string
	Status    string
	Tags      []string
	CreatedAt time.Time
	UpdatedAt time.Time
	CacheKey  string
}
