package docs

import (
	"fmt"
	"path/filepath"
	"rpl/internal/generator/parser/ast"
	targetpkg "rpl/internal/generator/target"
	"rpl/pkg/sdk"
	"sort"
	"strings"
)

const defaultOutputDir = "models"

func OutputPath(sourcePath string) string {
	absolute := strings.TrimSpace(sourcePath)
	if absolute == "" {
		return "README.md"
	}

	sourceDir := filepath.Dir(absolute)
	if filepath.Base(sourceDir) == "src" {
		return filepath.Join(filepath.Dir(sourceDir), "README.md")
	}

	return filepath.Join(sourceDir, "README.md")
}

func BuildReadme(file *ast.File, sourcePath string) string {
	title := readmeTitle(sourcePath)
	models := file.Models()
	targetLang := file.TargetLang()
	if strings.TrimSpace(targetLang) == "" {
		targetLang = targetpkg.DefaultLanguage
	}

	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	builder.WriteString("README generated by `rpl docs`.\n\n")

	builder.WriteString("## Overview\n\n")
	builder.WriteString("- Source schema: `")
	builder.WriteString(filepath.ToSlash(sourcePath))
	builder.WriteString("`\n")
	builder.WriteString("- Target language: `")
	builder.WriteString(targetLang)
	builder.WriteString("`\n")
	builder.WriteString("- Output directory: `")
	builder.WriteString(defaultOutputDir)
	builder.WriteString("/`\n")
	builder.WriteString("- Output package: `")
	builder.WriteString(targetPackage(targetLang))
	builder.WriteString("`\n")

	if attrs := runtimeIdentifiers(file); len(attrs) > 0 {
		builder.WriteString("- Attrs: ")
		builder.WriteString(joinCodeList(attrs))
		builder.WriteString("\n")
	}
	if imports := importSpecs(file); len(imports) > 0 {
		builder.WriteString("- External imports: ")
		builder.WriteString(joinCodeList(imports))
		builder.WriteString("\n")
	}
	builder.WriteString("\n")

	builder.WriteString("## Commands\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString("rpl gen ")
	builder.WriteString(filepath.ToSlash(sourcePath))
	builder.WriteString("\n")
	builder.WriteString("rpl docs ")
	builder.WriteString(filepath.ToSlash(sourcePath))
	builder.WriteString("\n")
	builder.WriteString("```\n\n")

	builder.WriteString("## Models\n\n")
	if len(models) == 0 {
		builder.WriteString("No models found.\n")
	} else {
		for i, model := range models {
			if model == nil {
				continue
			}
			builder.WriteString(renderModelSection(file, model))
			if i != len(models)-1 {
				builder.WriteString("\n")
			}
		}
	}

	builder.WriteString("\n## Generated Files\n\n")
	for _, item := range generatedFiles(file) {
		builder.WriteString("- `")
		builder.WriteString(item)
		builder.WriteString("`\n")
	}

	return builder.String()
}

func readmeTitle(sourcePath string) string {
	sourceName := strings.TrimSuffix(filepath.Base(strings.TrimSpace(sourcePath)), filepath.Ext(strings.TrimSpace(sourcePath)))
	if sourceName == "main" {
		sourceDir := filepath.Dir(strings.TrimSpace(sourcePath))
		if filepath.Base(sourceDir) == "src" {
			projectName := filepath.Base(filepath.Dir(sourceDir))
			if strings.TrimSpace(projectName) != "" {
				return projectName
			}
		}
	}
	if strings.TrimSpace(sourceName) == "" {
		return "RPL Schema"
	}
	return sourceName
}

func targetPackage(language string) string {
	renderer, ok := targetpkg.Lookup(language)
	if !ok {
		return "models"
	}
	if structured, ok := renderer.(targetpkg.StructuredRenderer); ok {
		return structured.RootPackageName()
	}
	return renderer.PackageName()
}

func runtimeIdentifiers(file *ast.File) []string {
	if file == nil {
		return nil
	}

	seen := make(map[string]struct{})
	items := make([]string, 0)
	for _, runtimeBlock := range file.Runtimes() {
		if runtimeBlock == nil {
			continue
		}
		for _, spec := range runtimeBlock.Specs {
			identifier := spec.Identifier()
			if strings.TrimSpace(identifier) == "" {
				continue
			}
			if _, ok := seen[identifier]; ok {
				continue
			}
			seen[identifier] = struct{}{}
			items = append(items, identifier)
		}
	}
	sort.Strings(items)
	return items
}

func importSpecs(file *ast.File) []string {
	if file == nil {
		return nil
	}

	seen := make(map[string]struct{})
	items := make([]string, 0)
	for _, importNode := range file.Imports() {
		if importNode == nil {
			continue
		}
		for _, spec := range importNode.Specs {
			value := strings.TrimSpace(spec.Path)
			if strings.TrimSpace(spec.Alias) != "" {
				value = spec.Alias + " " + value
			}
			if value == "" {
				continue
			}
			if _, ok := seen[value]; ok {
				continue
			}
			seen[value] = struct{}{}
			items = append(items, value)
		}
	}
	sort.Strings(items)
	return items
}

func renderModelSection(file *ast.File, model *ast.ModelAST) string {
	var builder strings.Builder
	builder.WriteString("### ")
	builder.WriteString(model.Name)
	builder.WriteString("\n\n")

	if comment := attrFirstString(model.FindAttr("comment")); comment != "" {
		builder.WriteString(comment)
		builder.WriteString("\n\n")
	}
	if strings.TrimSpace(model.GeneratedFrom) != "" {
		builder.WriteString("- Derived from: `")
		builder.WriteString(model.GeneratedFrom)
		builder.WriteString("`\n")
	}
	if strings.TrimSpace(model.GroupName) != "" {
		builder.WriteString("- Group: `")
		builder.WriteString(model.GroupName)
		builder.WriteString("`\n")
	}
	if attrs := renderAttrs(model.Attrs, "comment"); attrs != "" {
		builder.WriteString("- Model attrs: ")
		builder.WriteString(attrs)
		builder.WriteString("\n")
	}
	builder.WriteString("- Fields:\n")
	for _, field := range model.Fields {
		if field == nil {
			continue
		}

		builder.WriteString("  - `")
		builder.WriteString(field.Name)
		builder.WriteString(" ")
		builder.WriteString(renderType(field.Type))
		builder.WriteString("`")
		if field.Default != nil {
			builder.WriteString(" default `")
			builder.WriteString(renderExpr(field.Default))
			builder.WriteString("`")
		}

		fieldDetails := make([]string, 0, 2)
		if attrs := renderAttrs(field.Attrs); attrs != "" {
			fieldDetails = append(fieldDetails, "attrs: "+attrs)
		}
		if len(field.Methods) > 0 {
			fieldDetails = append(fieldDetails, "methods: "+renderMethods(file, field.Methods))
		}
		if len(fieldDetails) > 0 {
			builder.WriteString(" — ")
			builder.WriteString(strings.Join(fieldDetails, "; "))
		}
		builder.WriteString("\n")
	}

	return builder.String()
}

func generatedFiles(file *ast.File) []string {
	if file == nil {
		return nil
	}

	targetLang := targetpkg.NormalizeLanguage(file.TargetLang())
	renderer, ok := targetpkg.Lookup(targetLang)
	if !ok {
		return nil
	}

	files := make([]string, 0)
	seen := make(map[string]struct{})
	for _, model := range file.Models() {
		if model == nil {
			continue
		}

		layout := targetpkg.ResolveModelLayout(renderer, model.Name)
		files = addGeneratedFile(files, seen, filepath.ToSlash(filepath.Join(defaultOutputDir, layout.MainRelative)))
		if strings.TrimSpace(layout.FacadeRelative) != "" {
			files = addGeneratedFile(files, seen, filepath.ToSlash(filepath.Join(defaultOutputDir, layout.FacadeRelative)))
		}
		if modelUsesStdArtifacts(model) {
			files = addGeneratedFile(files, seen, filepath.ToSlash(filepath.Join(defaultOutputDir, layout.ModelDirName, "meta.gen.go")))
		}
		if modelUsesAttr(model, "validate") {
			files = addGeneratedFile(files, seen, filepath.ToSlash(filepath.Join(defaultOutputDir, layout.ModelDirName, "validation", "validation.gen.go")))
		}
		if modelUsesAttr(model, "sql") {
			for _, name := range []string{"schema.gen.go", "queries.gen.go", "scan.gen.go"} {
				files = addGeneratedFile(files, seen, filepath.ToSlash(filepath.Join(defaultOutputDir, layout.ModelDirName, "sql", name)))
			}
		}
		if modelUsesAttr(model, "grpc") {
			stem := sdk.SnakeCase(model.Name)
			for _, name := range []string{
				"proto.gen.go",
				"server.gen.go",
				"client.gen.go",
				stem + ".proto",
				stem + ".pb.go",
				stem + "_grpc.pb.go",
			} {
				files = addGeneratedFile(files, seen, filepath.ToSlash(filepath.Join(defaultOutputDir, layout.ModelDirName, "grpc", name)))
			}
		}
	}

	sort.Strings(files)
	return files
}

func addGeneratedFile(files []string, seen map[string]struct{}, name string) []string {
	if strings.TrimSpace(name) == "" {
		return files
	}
	if _, ok := seen[name]; ok {
		return files
	}
	seen[name] = struct{}{}
	return append(files, name)
}

func modelUsesStdArtifacts(model *ast.ModelAST) bool {
	if model == nil {
		return false
	}
	return modelUsesAttr(model, "std", "comment", "group", "ignore")
}

func modelUsesAttr(model *ast.ModelAST, namespace string, aliases ...string) bool {
	if model == nil {
		return false
	}

	match := func(attr ast.Attr) bool {
		if attrMatchesNamespace(attr, namespace) {
			return true
		}
		for _, alias := range aliases {
			if strings.EqualFold(strings.TrimSpace(attr.Name.String()), strings.TrimSpace(alias)) && strings.TrimSpace(attr.Package.String()) == "" {
				return true
			}
			if strings.EqualFold(strings.TrimSpace(attr.Identifier()), strings.TrimSpace(alias)) {
				return true
			}
		}
		return false
	}

	for _, attr := range model.Attrs {
		if match(attr) {
			return true
		}
	}
	for _, field := range model.Fields {
		if field == nil {
			continue
		}
		for _, attr := range field.Attrs {
			if match(attr) {
				return true
			}
		}
		for _, method := range field.Methods {
			for _, attr := range method.Attrs {
				if match(attr) {
					return true
				}
			}
		}
	}
	return false
}

func attrMatchesNamespace(attr ast.Attr, namespace string) bool {
	namespace = strings.TrimSpace(namespace)
	if namespace == "" {
		return false
	}
	if strings.EqualFold(strings.TrimSpace(attr.Package.String()), namespace) {
		return true
	}
	if strings.EqualFold(strings.TrimSpace(attr.Name.String()), namespace) {
		return true
	}
	return strings.EqualFold(strings.TrimSpace(attr.Identifier()), namespace)
}

func renderType(typeRef ast.TypeRef) string {
	name := strings.TrimSpace(typeRef.Name.String())
	if name == "" {
		name = "any"
	}
	if typeRef.IsList {
		name = "[]" + name
	}
	if typeRef.Optional {
		name += "?"
	}
	return name
}

func renderExpr(expr ast.Expr) string {
	switch value := expr.(type) {
	case ast.StringExpr:
		return fmt.Sprintf("%q", value.Value)
	case ast.NumberExpr:
		return value.Value
	case ast.BoolExpr:
		if value.Value {
			return "true"
		}
		return "false"
	case ast.NameExpr:
		return value.Name.String()
	case ast.GoExpr:
		return value.Text
	default:
		return ast.ExprString(expr)
	}
}

func renderAttrs(items []ast.Attr, skip ...string) string {
	if len(items) == 0 {
		return ""
	}

	skipSet := make(map[string]struct{}, len(skip))
	for _, item := range skip {
		skipSet[item] = struct{}{}
	}

	parts := make([]string, 0, len(items))
	for _, item := range items {
		if _, ok := skipSet[item.Identifier()]; ok {
			continue
		}
		parts = append(parts, "`"+renderAttr(item)+"`")
	}

	return strings.Join(parts, ", ")
}

func renderAttr(attr ast.Attr) string {
	var builder strings.Builder
	builder.WriteString("@")
	builder.WriteString(attr.Identifier())

	args := make([]string, 0, len(attr.Args)+len(attr.NamedArgs))
	for _, arg := range attr.Args {
		args = append(args, renderExpr(arg))
	}
	for _, item := range attr.NamedArgs {
		args = append(args, item.Name+": "+renderExpr(item.Value))
	}
	if len(args) == 0 {
		return builder.String()
	}

	builder.WriteString("(")
	builder.WriteString(strings.Join(args, ", "))
	builder.WriteString(")")
	return builder.String()
}

func renderMethods(file *ast.File, items []ast.FieldMethodAST) string {
	parts := make([]string, 0, len(items))
	for _, method := range items {
		params := make([]string, 0, len(method.Params))
		for _, param := range method.Params {
			params = append(params, param.Name+" "+renderType(resolveModelFieldType(file, param.Type)))
		}

		returns := make([]string, 0, len(method.Returns))
		for _, result := range method.Returns {
			returns = append(returns, renderType(resolveModelFieldType(file, result)))
		}

		signature := method.Name + "(" + strings.Join(params, ", ") + ")"
		if len(returns) > 0 {
			signature += " -> " + strings.Join(returns, ", ")
		}
		if attrs := renderAttrs(method.Attrs); attrs != "" {
			signature += " " + attrs
		}
		parts = append(parts, "`"+signature+"`")
	}
	return strings.Join(parts, ", ")
}

func resolveModelFieldType(file *ast.File, typeRef ast.TypeRef) ast.TypeRef {
	if file == nil || len(typeRef.Name.Parts) != 2 {
		return typeRef
	}

	modelName := strings.TrimSpace(typeRef.Name.Parts[0])
	fieldName := strings.TrimSpace(typeRef.Name.Parts[1])
	model, ok := file.FindModel(modelName)
	if !ok || model == nil {
		return typeRef
	}

	field, ok := model.FindField(fieldName)
	if !ok || field == nil {
		return typeRef
	}

	if len(field.Type.Name.Parts) == 2 {
		return resolveModelFieldType(file, field.Type)
	}

	return field.Type
}

func joinCodeList(items []string) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		parts = append(parts, "`"+item+"`")
	}
	return strings.Join(parts, ", ")
}

func attrFirstString(attr *ast.Attr, ok bool) string {
	if !ok || attr == nil {
		return ""
	}
	if len(attr.Args) > 0 {
		return strings.TrimSpace(ast.ExprString(attr.Args[0]))
	}
	for _, key := range []string{"text", "comment", "group", "name"} {
		if value, ok := attr.NamedArg(key); ok {
			return strings.TrimSpace(ast.ExprString(value))
		}
	}
	return ""
}
