// Code generated by RPL. DO NOT EDIT.
package validation

import (
	"errors"
	"fmt"
	modelpkg "m/src/user"
	"regexp"
)

var userPhonePattern = regexp.MustCompile("^\\+?[0-9][0-9\\s\\-()]{4,}$")

// Errors собирает все ошибки валидации для модели User.
func Errors(model modelpkg.User) []error {
	errs := make([]error, 0)
	if len(model.Name) < 2 {
		errs = append(errs, fmt.Errorf("Name is too short"))
	}
	if len(model.Name) > 33 {
		errs = append(errs, fmt.Errorf("Name is too long"))
	}
	if !userPhonePattern.MatchString(model.Phone) {
		errs = append(errs, fmt.Errorf("Phone must be phone"))
	}
	return errs
}

// Validate возвращает объединенную ошибку валидации для модели User.
func Validate(model modelpkg.User) error {
	errs := Errors(model)
	if len(errs) == 0 {
		return nil
	}

	return errors.Join(errs...)
}
