package main

import (
	"encoding/json"
	"fmt"
	"rpl/pkg/sdk"
	"sort"
	"strings"
)

type wasmSchema struct {
	Format     string       `json:"format"`
	Package    string       `json:"package"`
	World      string       `json:"world"`
	Interface  string       `json:"interface"`
	Guest      string       `json:"guest"`
	Hosts      []string     `json:"hosts"`
	Wasmtime   string       `json:"wasmtime"`
	WITBindgen string       `json:"wit_bindgen"`
	Models     []wasmModel  `json:"models"`
	Methods    []wasmMethod `json:"methods"`
}

func generateWASM(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	plan, err := buildWASMPlan(req)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}
	return generateWASMResponse(plan), nil
}

func generateWASMResponse(plan *wasmPlan) sdk.GenerateResponse {
	if plan == nil {
		return sdk.GenerateResponse{}
	}
	root := "wasm/" + plan.Root + "/"
	wit := generateWIT(plan)
	files := []sdk.GeneratedFile{
		{Path: root + "wit/world.wit", Content: wit},
		{Path: root + "plugin.toml", Content: generateWASMManifest(plan)},
		{Path: root + "schema.json", Content: generateWASMSchema(plan)},
		{Path: root + "README.md", Content: generateWASMReadme(plan)},
	}
	if plan.Guest == "rust" {
		files = append(files,
			sdk.GeneratedFile{Path: root + "guest/rust/Cargo.toml", Content: generateWASMGuestCargo(plan)},
			sdk.GeneratedFile{Path: root + "guest/rust/src/lib.rs", Content: generateWASMGuestRust(plan)},
			sdk.GeneratedFile{Path: root + "guest/rust/wit/world.wit", Content: wit},
		)
	}
	if plan.Hosts["rust"] {
		files = append(files,
			sdk.GeneratedFile{Path: root + "host/rust/Cargo.toml", Content: generateWASMHostCargo(plan)},
			sdk.GeneratedFile{Path: root + "host/rust/src/lib.rs", Content: generateWASMHostRust(plan)},
			sdk.GeneratedFile{Path: root + "host/rust/wit/world.wit", Content: wit},
		)
	}
	return sdk.GenerateResponse{Files: files}
}

func generateWIT(plan *wasmPlan) string {
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by rpl:wasm. DO NOT EDIT.\npackage %s;\n\n", plan.Package)
	fmt.Fprintf(&out, "interface %s {\n", wasmWITIdent(plan.Interface))
	for _, model := range plan.Models {
		fmt.Fprintf(&out, "  record %s {\n", wasmWITIdent(model.WITName))
		for _, field := range model.Fields {
			fmt.Fprintf(&out, "    %s: %s,\n", wasmWITIdent(field.WITName), wasmWITType(field.Type))
		}
		out.WriteString("  }\n\n")
	}
	for _, method := range plan.Methods {
		fmt.Fprintf(&out, "  %s: func(", wasmWITIdent(method.WITName))
		for index, param := range method.Params {
			if index > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%s: %s", wasmWITIdent(param.WITName), wasmWITType(param.Type))
		}
		out.WriteString(")")
		if result := wasmWITMethodResult(method); result != "" {
			fmt.Fprintf(&out, " -> %s", result)
		}
		out.WriteString(";\n")
	}
	fmt.Fprintf(&out, "}\n\nworld %s {\n  export %s;\n}\n", wasmWITIdent(plan.World), wasmWITIdent(plan.Interface))
	return out.String()
}

func wasmWITType(typeRef sdk.TypeRef) string {
	base := typeRef.BaseName()
	var value string
	switch base {
	case "bool", "string":
		value = base
	case "int8":
		value = "s8"
	case "int16":
		value = "s16"
	case "int32":
		value = "s32"
	case "int", "int64":
		value = "s64"
	case "byte", "uint8":
		value = "u8"
	case "uint16":
		value = "u16"
	case "uint32":
		value = "u32"
	case "uint", "uint64":
		value = "u64"
	case "float32":
		value = "f32"
	case "float64":
		value = "f64"
	default:
		value = wasmWITIdent(wasmKebab(base))
	}
	if typeRef.IsList {
		value = "list<" + value + ">"
	}
	if typeRef.Optional {
		value = "option<" + value + ">"
	}
	return value
}

func wasmWITMethodResult(method wasmMethod) string {
	value := ""
	switch len(method.Returns) {
	case 0:
	case 1:
		value = wasmWITType(method.Returns[0])
	default:
		items := make([]string, 0, len(method.Returns))
		for _, result := range method.Returns {
			items = append(items, wasmWITType(result))
		}
		value = "tuple<" + strings.Join(items, ", ") + ">"
	}
	if method.HasError {
		if value == "" {
			value = "_"
		}
		return "result<" + value + ", string>"
	}
	return value
}

func generateWASMManifest(plan *wasmPlan) string {
	return fmt.Sprintf(`# Generated by rpl:wasm. Safe capabilities are disabled by default.
name = %q
version = %q
world = %q
wit-package = %q
entrypoint = "component.wasm"
checksum = ""

[permissions]
filesystem = false
network = false
stdin = false
stdout = false
environment = []

[resources]
max-memory-bytes = %d
max-execution-time-ms = %d
fuel = %d
`, plan.Root, plan.Version, plan.Namespace+":"+plan.PackageName+"/"+plan.World, plan.Package, plan.MemoryBytes, plan.TimeoutMS, plan.Fuel)
}

func generateWASMSchema(plan *wasmPlan) string {
	hosts := make([]string, 0, len(plan.Hosts))
	for host, enabled := range plan.Hosts {
		if enabled {
			hosts = append(hosts, host)
		}
	}
	sort.Strings(hosts)
	body, err := json.MarshalIndent(wasmSchema{
		Format: "rpl.wasm.ir/v1", Package: plan.Package, World: plan.World, Interface: plan.Interface,
		Guest: plan.Guest, Hosts: hosts, Wasmtime: wasmtimeVersion, WITBindgen: witBindgenVersion,
		Models: plan.Models, Methods: plan.Methods,
	}, "", "  ")
	if err != nil {
		return fmt.Sprintf("{\"error\":%q}\n", err.Error())
	}
	return string(body) + "\n"
}

func generateWASMGuestCargo(plan *wasmPlan) string {
	return fmt.Sprintf(`[package]
name = %q
version = %q
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = %q
`, strings.ReplaceAll(plan.Root, "-", "_")+"_guest", plan.Version, witBindgenVersion)
}

func generateWASMGuestRust(plan *wasmPlan) string {
	module := "exports::" + wasmRustIdent(plan.Namespace) + "::" + wasmRustIdent(plan.PackageName) + "::" + wasmRustIdent(plan.Interface)
	var out strings.Builder
	out.WriteString("// Code generated by rpl:wasm. Implement the marked method bodies.\n")
	fmt.Fprintf(&out, "wit_bindgen::generate!({ path: \"wit\", world: %q });\n\n", plan.World)
	fmt.Fprintf(&out, "use %s::Guest;\n\npub struct Component;\n\nimpl Guest for Component {\n", module)
	for _, method := range plan.Methods {
		fmt.Fprintf(&out, "    fn %s(", wasmRustIdent(method.WITName))
		for index, param := range method.Params {
			if index > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%s: %s", wasmRustIdent(param.WITName), wasmRustGuestType(plan, param.Type, module))
		}
		fmt.Fprintf(&out, ") -> %s {\n", wasmRustGuestResult(plan, method, module))
		for _, param := range method.Params {
			fmt.Fprintf(&out, "        let _ = %s;\n", wasmRustIdent(param.WITName))
		}
		fmt.Fprintf(&out, "        todo!(%q)\n    }\n", "implement "+method.WITName)
	}
	out.WriteString("}\n\nexport!(Component);\n")
	return out.String()
}

func wasmRustGuestType(plan *wasmPlan, typeRef sdk.TypeRef, module string) string {
	base := typeRef.BaseName()
	var value string
	switch base {
	case "bool", "String", "string":
		if base == "string" {
			value = "String"
		} else {
			value = base
		}
	case "int8":
		value = "i8"
	case "int16":
		value = "i16"
	case "int32":
		value = "i32"
	case "int", "int64":
		value = "i64"
	case "byte", "uint8":
		value = "u8"
	case "uint16":
		value = "u16"
	case "uint32":
		value = "u32"
	case "uint", "uint64":
		value = "u64"
	case "float32":
		value = "f32"
	case "float64":
		value = "f64"
	default:
		value = module + "::" + wasmRustTypeName(base)
	}
	if typeRef.IsList {
		value = "Vec<" + value + ">"
	}
	if typeRef.Optional {
		value = "Option<" + value + ">"
	}
	return value
}

func wasmRustGuestResult(plan *wasmPlan, method wasmMethod, module string) string {
	value := "()"
	if len(method.Returns) == 1 {
		value = wasmRustGuestType(plan, method.Returns[0], module)
	} else if len(method.Returns) > 1 {
		items := make([]string, 0, len(method.Returns))
		for _, result := range method.Returns {
			items = append(items, wasmRustGuestType(plan, result, module))
		}
		value = "(" + strings.Join(items, ", ") + ")"
	}
	if method.HasError {
		return "Result<" + value + ", String>"
	}
	return value
}

func generateWASMHostCargo(plan *wasmPlan) string {
	return fmt.Sprintf(`[package]
name = %q
version = %q
edition = "2024"

[dependencies]
anyhow = "1"
wasmtime = { version = %q, features = ["component-model", "runtime"] }
`, strings.ReplaceAll(plan.Root, "-", "_")+"_host", plan.Version, wasmtimeVersion)
}

func generateWASMHostRust(plan *wasmPlan) string {
	worldType := wasmRustTypeName(plan.World)
	return fmt.Sprintf(`// Code generated by rpl:wasm. DO NOT EDIT.
use anyhow::{anyhow, Result};
use wasmtime::{Config, Engine, Store, StoreLimits, StoreLimitsBuilder};
use wasmtime::component::{Component, Linker};

pub mod bindings {
    wasmtime::component::bindgen!({ path: "wit", world: %q });
}

pub const MAX_MEMORY_BYTES: usize = %d;
pub const MAX_EXECUTION_TIME_MS: u64 = %d;
pub const FUEL: u64 = %d;

pub struct PluginEngine {
    engine: Engine,
}

struct HostState {
    limits: StoreLimits,
}

impl PluginEngine {
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        config.consume_fuel(true);
        config.epoch_interruption(true);
        Ok(Self { engine: Engine::new(&config)? })
    }

    pub fn load(&self, path: impl AsRef<std::path::Path>) -> Result<Plugin> {
        let component = Component::from_file(&self.engine, path.as_ref())
			.map_err(|error| anyhow!("load WASM component {}: {}", path.as_ref().display(), error))?;
		let linker = Linker::<HostState>::new(&self.engine);
		let limits = StoreLimitsBuilder::new()
			.memory_size(MAX_MEMORY_BYTES)
			.instances(10)
			.tables(10)
			.build();
		let mut store = Store::new(&self.engine, HostState { limits });
		store.limiter(|state| &mut state.limits);
        store.set_fuel(FUEL)?;
        store.set_epoch_deadline(1);
        let bindings = bindings::%s::instantiate(&mut store, &component, &linker)
			.map_err(|error| anyhow!("component does not implement the required WIT world: {}", error))?;
        Ok(Plugin { store, bindings })
    }

    pub fn interrupt_running_calls(&self) {
        self.engine.increment_epoch();
    }
}

pub struct Plugin {
	store: Store<HostState>,
    bindings: bindings::%s,
}

impl Plugin {
	pub fn typed<R>(&mut self, call: impl FnOnce(&bindings::%s, &mut Store<HostState>) -> Result<R>) -> Result<R> {
        call(&self.bindings, &mut self.store)
    }
}
`, plan.World, plan.MemoryBytes, plan.TimeoutMS, plan.Fuel, worldType, worldType, worldType)
}

func generateWASMReadme(plan *wasmPlan) string {
	return fmt.Sprintf("# %s WebAssembly component\n\n"+
		"Generated from RPL as WIT package `%s` and world `%s`.\n\n"+
		"## Guest\n\n"+
		"Implement the `todo!` method bodies in `guest/rust/src/lib.rs`, install a Component Model capable Rust toolchain, and build the component. The generated crate uses `wit-bindgen %s` and never exposes linear-memory pointers to application code.\n\n"+
		"## Host\n\n"+
		"`host/rust` contains Wasmtime %s typed bindings. `PluginEngine::load` validates that the component implements the generated world. Call exported operations through `Plugin::typed` and the generated `%s` binding.\n\n"+
		"The manifest denies filesystem, network, stdio, and environment access. The host enforces memory and fuel limits. The embedding application must schedule `interrupt_running_calls` after %d ms to enforce the wall-clock timeout.\n\n"+
		"Go Component Model guest/host output is intentionally not advertised by this MVP because it is not covered by this project's end-to-end toolchain tests yet.\n",
		plan.Root, plan.Package, plan.World, witBindgenVersion, wasmtimeVersion, wasmRustTypeName(plan.World), plan.TimeoutMS)
}
