// Code generated by RPL. DO NOT EDIT.
package mongodb

import (
	modelpkg ".."
	"context"
	"fmt"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"sort"
	"strings"
	"time"
)

type userMongoDocument struct {
	ID        primitive.ObjectID `bson:"_id,omitempty"`
	Email     string             `bson:"email"`
	Username  string             `bson:"username"`
	Status    string             `bson:"status"`
	Tags      []string           `bson:"tags"`
	CreatedAt time.Time          `bson:"created_at"`
	UpdatedAt time.Time          `bson:"updated_at"`
}

func userMongoWrap(model modelpkg.User, includeDefaults bool, touchUpdatedAt bool) (userMongoDocument, error) {
	doc := userMongoDocument{}
	if strings.TrimSpace(model.ID) != "" {
		parsed, err := primitive.ObjectIDFromHex(model.ID)
		if err != nil {
			return doc, fmt.Errorf("invalid object id for field _id: %w", err)
		}
		doc.ID = parsed
	}
	doc.Email = model.Email
	doc.Username = model.Username
	doc.Status = model.Status
	doc.Tags = model.Tags
	if includeDefaults && model.CreatedAt.IsZero() {
		doc.CreatedAt = time.Now()
	} else {
		doc.CreatedAt = model.CreatedAt
	}
	if touchUpdatedAt {
		doc.UpdatedAt = time.Now()
	} else if includeDefaults && strings.EqualFold("now", "now") && model.UpdatedAt.IsZero() {
		doc.UpdatedAt = time.Now()
	} else {
		doc.UpdatedAt = model.UpdatedAt
	}
	return doc, nil
}

func userMongoUnwrap(doc userMongoDocument) modelpkg.User {
	model := modelpkg.User{}
	if !doc.ID.IsZero() {
		model.ID = doc.ID.Hex()
	}
	model.Email = doc.Email
	model.Username = doc.Username
	model.Status = doc.Status
	model.Tags = doc.Tags
	model.CreatedAt = doc.CreatedAt
	model.UpdatedAt = doc.UpdatedAt
	return model
}

// userMongoDocumentMap converts a model into a MongoDB document.
func userMongoDocumentMap(model modelpkg.User) (bson.M, error) {
	wrapped, err := userMongoWrap(model, true, true)
	if err != nil {
		return nil, err
	}
	body, err := bson.Marshal(wrapped)
	if err != nil {
		return nil, err
	}
	var document bson.M
	if err := bson.Unmarshal(body, &document); err != nil {
		return nil, err
	}
	return document, nil
}

// userMongoUpdateDocument builds a `$set`-ready document for updates.
func userMongoUpdateDocument(model modelpkg.User) (bson.M, error) {
	wrapped, err := userMongoWrap(model, false, true)
	if err != nil {
		return nil, err
	}
	body, err := bson.Marshal(wrapped)
	if err != nil {
		return nil, err
	}
	var document bson.M
	if err := bson.Unmarshal(body, &document); err != nil {
		return nil, err
	}
	delete(document, "_id")
	return document, nil
}

// userMongoDocuments converts a model slice into MongoDB insert payloads.
func userMongoDocuments(models []modelpkg.User) ([]any, error) {
	items := make([]any, 0, len(models))
	for _, model := range models {
		document, err := userMongoDocumentMap(model)
		if err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	return items, nil
}

// userMongoFromDocument decodes a raw MongoDB document into the model.
func userMongoFromDocument(document bson.M) (modelpkg.User, error) {
	body, err := bson.Marshal(document)
	if err != nil {
		return modelpkg.User{}, err
	}
	var wrapped userMongoDocument
	if err := bson.Unmarshal(body, &wrapped); err != nil {
		return modelpkg.User{}, err
	}
	return userMongoUnwrap(wrapped), nil
}

// userMongoDecodeOne decodes one MongoDB result into the model.
func userMongoDecodeOne(result *mongo.SingleResult) (modelpkg.User, error) {
	var wrapped userMongoDocument
	if err := result.Decode(&wrapped); err != nil {
		return modelpkg.User{}, err
	}
	return userMongoUnwrap(wrapped), nil
}

// userMongoDecodeMany decodes a MongoDB cursor into model items.
func userMongoDecodeMany(ctx context.Context, cursor *mongo.Cursor) ([]modelpkg.User, error) {
	defer cursor.Close(ctx)
	items := make([]modelpkg.User, 0)
	for cursor.Next(ctx) {
		var wrapped userMongoDocument
		if err := cursor.Decode(&wrapped); err != nil {
			return nil, err
		}
		items = append(items, userMongoUnwrap(wrapped))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// userMongoIDFilter builds a MongoDB filter for the primary identifier field.
func userMongoIDFilter(id any) (bson.M, error) {
	value, err := userMongoNormalizeFilterValue("_id", id)
	if err != nil {
		return nil, err
	}
	return bson.M{"_id": value}, nil
}

// userMongoNormalizeFieldName maps model field names to BSON field names.
func userMongoNormalizeFieldName(name string) (string, bool) {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return "", false
	}
	if strings.HasPrefix(trimmed, "$") {
		return trimmed, true
	}
	switch trimmed {
	case "ID", "_id":
		return "_id", true
	case "Email", "email":
		return "email", true
	case "Username", "username":
		return "username", true
	case "Status", "status":
		return "status", true
	case "Tags", "tags":
		return "tags", true
	case "CreatedAt", "created_at":
		return "created_at", true
	case "UpdatedAt", "updated_at":
		return "updated_at", true
	default:
		return "", false
	}
}

// userMongoNormalizeFilterValue normalizes values for BSON-aware filters.
func userMongoNormalizeFilterValue(fieldName string, value any) (any, error) {
	normalized, ok := userMongoNormalizeFieldName(fieldName)
	if !ok {
		return nil, fmt.Errorf("unknown mongodb field %q", fieldName)
	}
	switch normalized {
	case "_id":
		switch typed := value.(type) {
		case nil:
			return nil, nil
		case primitive.ObjectID:
			return typed, nil
		case *primitive.ObjectID:
			return typed, nil
		case string:
			if strings.TrimSpace(typed) == "" {
				return primitive.NilObjectID, nil
			}
			return primitive.ObjectIDFromHex(strings.TrimSpace(typed))
		case *string:
			if typed == nil || strings.TrimSpace(*typed) == "" {
				return nil, nil
			}
			value, err := primitive.ObjectIDFromHex(strings.TrimSpace(*typed))
			if err != nil {
				return nil, err
			}
			return value, nil
		default:
			return nil, fmt.Errorf("unsupported object id value %T", value)
		}
	case "email":
		return value, nil
	case "username":
		return value, nil
	case "status":
		return value, nil
	case "tags":
		return value, nil
	case "created_at":
		return value, nil
	case "updated_at":
		return value, nil
	default:
		return value, nil
	}
}

// userMongoFilter builds a normalized MongoDB filter document.
func userMongoFilter(filters map[string]any) (bson.M, error) {
	if len(filters) == 0 {
		return bson.M{}, nil
	}
	keys := make([]string, 0, len(filters))
	for key := range filters {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	result := bson.M{}
	for _, key := range keys {
		if strings.HasPrefix(key, "$") {
			result[key] = filters[key]
			continue
		}
		normalized, ok := userMongoNormalizeFieldName(key)
		if !ok {
			return nil, fmt.Errorf("unknown mongodb filter field %q", key)
		}
		value, err := userMongoNormalizeFilterValue(normalized, filters[key])
		if err != nil {
			return nil, err
		}
		result[normalized] = value
	}
	return result, nil
}

// userMongoUpdateFieldsDocument normalizes a flat update payload.
func userMongoUpdateFieldsDocument(updates map[string]any) (bson.M, error) {
	if len(updates) == 0 {
		return bson.M{}, nil
	}
	result := bson.M{}
	for key, value := range updates {
		if strings.HasPrefix(strings.TrimSpace(key), "$") {
			result[key] = value
			continue
		}
		normalized, ok := userMongoNormalizeFieldName(key)
		if !ok {
			return nil, fmt.Errorf("unknown mongodb update field %q", key)
		}
		normalizedValue, err := userMongoNormalizeFilterValue(normalized, value)
		if err != nil {
			return nil, err
		}
		result[normalized] = normalizedValue
	}
	return result, nil
}

// userMongoSearchFilter builds a case-insensitive `$or` regex filter.
func userMongoSearchFilter(term string) bson.M {
	trimmed := strings.TrimSpace(term)
	if trimmed == "" || len(userMongoSearchFields) == 0 {
		return bson.M{}
	}
	return bson.M{"$or": []bson.M{{"email": bson.M{"$regex": trimmed, "$options": "i"}}, {"username": bson.M{"$regex": trimmed, "$options": "i"}}, {"tags": bson.M{"$regex": trimmed, "$options": "i"}}}}
}

// userMongoSort builds a MongoDB sort document.
func userMongoSort(orderBy string, descending bool) bson.D {
	name := strings.TrimSpace(orderBy)
	if normalized, ok := userMongoNormalizeFieldName(name); ok {
		name = normalized
	}
	if name == "" {
		name = "username"
	}
	order := 1
	if descending {
		order = -1
	}
	return bson.D{{Key: name, Value: order}}
}
