// Code generated by RPL. DO NOT EDIT.
package mongodb

import (
	modelpkg ".."
	"context"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// userMongoInsertOne inserts one model into MongoDB.
func userMongoInsertOne(ctx context.Context, db *mongo.Database, model modelpkg.User) error {
	document, err := userMongoDocumentMap(model)
	if err != nil {
		return err
	}
	_, err = userMongoCollection(db).InsertOne(ctx, document)
	return err
}

// userMongoInsertMany inserts multiple models into MongoDB.
func userMongoInsertMany(ctx context.Context, db *mongo.Database, models []modelpkg.User) error {
	documents, err := userMongoDocuments(models)
	if err != nil {
		return err
	}
	if len(documents) == 0 {
		return nil
	}
	_, err = userMongoCollection(db).InsertMany(ctx, documents)
	return err
}

// userMongoFindOne finds one MongoDB document by filter.
func userMongoFindOne(ctx context.Context, db *mongo.Database, filters map[string]any) (modelpkg.User, error) {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return modelpkg.User{}, err
	}
	result := userMongoCollection(db).FindOne(ctx, filter)
	return userMongoDecodeOne(result)
}

// userMongoFindByID finds a MongoDB document by the primary identifier field.
func userMongoFindByID(ctx context.Context, db *mongo.Database, id any) (modelpkg.User, error) {
	filter, err := userMongoIDFilter(id)
	if err != nil {
		return modelpkg.User{}, err
	}
	result := userMongoCollection(db).FindOne(ctx, filter)
	return userMongoDecodeOne(result)
}

// userMongoFindMany finds multiple MongoDB documents with paging and sorting.
func userMongoFindMany(ctx context.Context, db *mongo.Database, filters map[string]any, limit int64, skip int64, orderBy string, descending bool) ([]modelpkg.User, error) {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return nil, err
	}
	findOptions := options.Find()
	if limit > 0 {
		findOptions.SetLimit(limit)
	}
	if skip > 0 {
		findOptions.SetSkip(skip)
	}
	findOptions.SetSort(userMongoSort(orderBy, descending))
	cursor, err := userMongoCollection(db).Find(ctx, filter, findOptions)
	if err != nil {
		return nil, err
	}
	return userMongoDecodeMany(ctx, cursor)
}

// userMongoList lists MongoDB documents with paging and sorting.
func userMongoList(ctx context.Context, db *mongo.Database, limit int64, skip int64, orderBy string, descending bool) ([]modelpkg.User, error) {
	return userMongoFindMany(ctx, db, bson.M{}, limit, skip, orderBy, descending)
}

// userMongoSearch performs a generated text-style search across searchable fields.
func userMongoSearch(ctx context.Context, db *mongo.Database, term string, limit int64, skip int64, orderBy string, descending bool) ([]modelpkg.User, error) {
	return userMongoFindMany(ctx, db, userMongoSearchFilter(term), limit, skip, orderBy, descending)
}

// userMongoCount counts MongoDB documents matching the filter.
func userMongoCount(ctx context.Context, db *mongo.Database, filters map[string]any) (int64, error) {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return 0, err
	}
	return userMongoCollection(db).CountDocuments(ctx, filter)
}

// userMongoExists checks whether at least one MongoDB document matches the filter.
func userMongoExists(ctx context.Context, db *mongo.Database, filters map[string]any) (bool, error) {
	count, err := userMongoCount(ctx, db, filters)
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// userMongoReplaceOne replaces one MongoDB document by filter.
func userMongoReplaceOne(ctx context.Context, db *mongo.Database, model modelpkg.User, filters map[string]any, upsert bool) error {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return err
	}
	document, err := userMongoDocumentMap(model)
	if err != nil {
		return err
	}
	_, err = userMongoCollection(db).ReplaceOne(ctx, filter, document, options.Replace().SetUpsert(upsert))
	return err
}

// userMongoReplaceByID replaces one MongoDB document by primary identifier.
func userMongoReplaceByID(ctx context.Context, db *mongo.Database, id any, model modelpkg.User, upsert bool) error {
	filter, err := userMongoIDFilter(id)
	if err != nil {
		return err
	}
	return userMongoReplaceOne(ctx, db, model, filter, upsert)
}

// userMongoUpdateFields updates one MongoDB document with a flat `$set` payload.
func userMongoUpdateFields(ctx context.Context, db *mongo.Database, filters map[string]any, updates map[string]any, upsert bool) error {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return err
	}
	updateFields, err := userMongoUpdateFieldsDocument(updates)
	if err != nil {
		return err
	}
	if len(updateFields) == 0 {
		return nil
	}
	_, err = userMongoCollection(db).UpdateOne(ctx, filter, bson.M{"$set": updateFields}, options.Update().SetUpsert(upsert))
	return err
}

// userMongoUpdateManyFields updates many MongoDB documents with a flat `$set` payload.
func userMongoUpdateManyFields(ctx context.Context, db *mongo.Database, filters map[string]any, updates map[string]any, upsert bool) error {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return err
	}
	updateFields, err := userMongoUpdateFieldsDocument(updates)
	if err != nil {
		return err
	}
	if len(updateFields) == 0 {
		return nil
	}
	_, err = userMongoCollection(db).UpdateMany(ctx, filter, bson.M{"$set": updateFields}, options.Update().SetUpsert(upsert))
	return err
}

// userMongoUpdateModel updates one MongoDB document from the model payload.
func userMongoUpdateModel(ctx context.Context, db *mongo.Database, filters map[string]any, model modelpkg.User, upsert bool) error {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return err
	}
	updateFields, err := userMongoUpdateDocument(model)
	if err != nil {
		return err
	}
	if len(updateFields) == 0 {
		return nil
	}
	_, err = userMongoCollection(db).UpdateOne(ctx, filter, bson.M{"$set": updateFields}, options.Update().SetUpsert(upsert))
	return err
}

// userMongoUpdateByID updates one MongoDB document by primary identifier.
func userMongoUpdateByID(ctx context.Context, db *mongo.Database, id any, model modelpkg.User, upsert bool) error {
	filter, err := userMongoIDFilter(id)
	if err != nil {
		return err
	}
	return userMongoUpdateModel(ctx, db, filter, model, upsert)
}

// userMongoDeleteOne deletes one MongoDB document by filter.
func userMongoDeleteOne(ctx context.Context, db *mongo.Database, filters map[string]any) error {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return err
	}
	_, err = userMongoCollection(db).DeleteOne(ctx, filter)
	return err
}

// userMongoDeleteMany deletes many MongoDB documents by filter.
func userMongoDeleteMany(ctx context.Context, db *mongo.Database, filters map[string]any) error {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return err
	}
	_, err = userMongoCollection(db).DeleteMany(ctx, filter)
	return err
}

// userMongoDeleteByID deletes one MongoDB document by primary identifier.
func userMongoDeleteByID(ctx context.Context, db *mongo.Database, id any) error {
	filter, err := userMongoIDFilter(id)
	if err != nil {
		return err
	}
	return userMongoDeleteOne(ctx, db, filter)
}

// userMongoDistinct returns distinct values for a generated MongoDB field.
func userMongoDistinct(ctx context.Context, db *mongo.Database, fieldName string, filters map[string]any) ([]any, error) {
	filter, err := userMongoFilter(filters)
	if err != nil {
		return nil, err
	}
	normalized, ok := userMongoNormalizeFieldName(fieldName)
	if !ok {
		return nil, nil
	}
	return userMongoCollection(db).Distinct(ctx, normalized, filter)
}

// userMongoAggregate runs an aggregation pipeline and decodes typed results.
func userMongoAggregate(ctx context.Context, db *mongo.Database, pipeline mongo.Pipeline) ([]modelpkg.User, error) {
	cursor, err := userMongoCollection(db).Aggregate(ctx, pipeline)
	if err != nil {
		return nil, err
	}
	return userMongoDecodeMany(ctx, cursor)
}

// userMongoWatch opens a MongoDB change stream for the collection.
func userMongoWatch(ctx context.Context, db *mongo.Database, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return userMongoCollection(db).Watch(ctx, pipeline)
}
