// Code generated by RPL. DO NOT EDIT.
package mongodb

import (
	"context"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const userMongoDatabaseName = "mongodb"

const userMongoCollectionName = "users"

var userMongoFieldNames = []string{"_id", "email", "username", "status", "tags", "created_at", "updated_at"}

var userMongoSearchFields = []string{"email", "username", "tags"}

var userMongoSortFields = []string{"username", "status", "created_at", "updated_at"}

// userMongoCollection returns the typed MongoDB collection handle.
func userMongoCollection(db *mongo.Database) *mongo.Collection {
	return db.Collection(userMongoCollectionName)
}

// userMongoDatabase returns the configured MongoDB database name.
func userMongoDatabase() string {
	return userMongoDatabaseName
}

// userMongoCollectionLabel returns the configured MongoDB collection name.
func userMongoCollectionLabel() string {
	return userMongoCollectionName
}

// userMongoIndexes returns all generated MongoDB indexes for the model.
func userMongoIndexes() []mongo.IndexModel {
	return []mongo.IndexModel{
		{Keys: bson.D{{Key: "_id", Value: 1}}, Options: options.Index().SetName("users__id_idx").SetUnique(true)},
		{Keys: bson.D{{Key: "email", Value: 1}}, Options: options.Index().SetName("users_email_idx").SetUnique(true)},
		{Keys: bson.D{{Key: "username", Value: 1}}, Options: options.Index().SetName("users_username_idx")},
		{Keys: bson.D{{Key: "status", Value: 1}}, Options: options.Index().SetName("users_status_idx")},
		{Keys: bson.D{{Key: "email", Value: "text"}, {Key: "username", Value: "text"}, {Key: "tags", Value: "text"}}, Options: options.Index().SetName("users_search_text")},
	}
}

// userMongoEnsureIndexes creates all generated MongoDB indexes.
func userMongoEnsureIndexes(ctx context.Context, db *mongo.Database) error {
	indexes := userMongoIndexes()
	if len(indexes) == 0 {
		return nil
	}
	_, err := userMongoCollection(db).Indexes().CreateMany(ctx, indexes)
	return err
}
