// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	"fmt"
	modelpkg "m/src/user"
	"sort"
	"strings"
)

// userSQLBuildWhere собирает SQL WHERE-часть и аргументы из карты фильтров.
func userSQLBuildWhere(filters map[string]any, startIndex int) (string, []any, error) {
	if len(filters) == 0 {
		return "", nil, nil
	}

	keys := make([]string, 0, len(filters))
	for key := range filters {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	args := make([]any, 0, len(keys))

	for _, key := range keys {
		column, ok := userSQLNormalizeColumnName(key)
		if !ok {
			return "", nil, fmt.Errorf("unknown sql filter column %q", key)
		}

		value, err := userSQLNormalizeFilterValue(column, filters[key])
		if err != nil {
			return "", nil, err
		}

		if value == nil {
			parts = append(parts, column+" IS NULL")
			continue
		}

		args = append(args, value)
		parts = append(parts, fmt.Sprintf("%s = %s", column, userSQLPlaceholder(column, startIndex+len(args)-1)))
	}

	return " WHERE " + strings.Join(parts, " AND "), args, nil
}

// userSQLAppendPagination безопасно добавляет LIMIT/OFFSET для выбранного SQL-диалекта.
func userSQLAppendPagination(query string, args []any, limit int, offset int) (string, []any) {
	if limit > 0 {
		args = append(args, limit)
		query += " LIMIT " + userSQLPlaceholder("", len(args))
	}
	if offset > 0 {
		args = append(args, offset)
		query += " OFFSET " + userSQLPlaceholder("", len(args))
	}
	return query, args
}

// userSQLQueryMany выполняет SQL-запрос и собирает список моделей User.
func userSQLQueryMany(ctx context.Context, db Executor, query string, args ...any) ([]modelpkg.User, error) {
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]modelpkg.User, 0)
	for rows.Next() {
		var item modelpkg.User
		if err := userSQLScan(rows, &item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SQLInit создает таблицу и вспомогательные индексы для модели User.
func Init(ctx context.Context, db Executor) error {
	for _, statement := range userSQLCreateStatements {
		if strings.TrimSpace(statement) == "" {
			continue
		}

		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}

	return nil
}

// SQLCreate вставляет текущую модель User в базу данных.
func Create(ctx context.Context, db Executor, model modelpkg.User) error {
	values, err := userSQLDriverValues(model)
	if err != nil {
		return err
	}

	_, err = db.ExecContext(ctx, userSQLInsertStatement, values...)
	return err
}

// SQLGet находит одну модель User по фильтрам.
func Get(ctx context.Context, db Executor, filters map[string]any) (modelpkg.User, error) {
	if len(filters) == 0 {
		return modelpkg.User{}, fmt.Errorf("SQLGet requires at least one filter")
	}

	where, args, err := userSQLBuildWhere(filters, 1)
	if err != nil {
		return modelpkg.User{}, err
	}

	query := userSQLSelectStatement + where + " LIMIT 1"
	row := db.QueryRowContext(ctx, query, args...)
	var item modelpkg.User
	if err := userSQLScan(row, &item); err != nil {
		return modelpkg.User{}, err
	}

	return item, nil
}

// SQLUpdate обновляет запись модели User по переданным фильтрам.
func Update(ctx context.Context, db Executor, model modelpkg.User, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLUpdate requires at least one filter")
	}

	assignments, args, err := userSQLBuildUpdateAssignments(model, 1)
	if err != nil {
		return err
	}

	where, whereArgs, err := userSQLBuildWhere(filters, len(args)+1)
	if err != nil {
		return err
	}

	query := "UPDATE " + userSQLTableName + " SET " + assignments + where
	_, err = db.ExecContext(ctx, query, append(args, whereArgs...)...)
	return err
}

// SQLUpsert создает или обновляет модель User по уникальным колонкам.
func Upsert(ctx context.Context, db Executor, model modelpkg.User) error {
	statement := userSQLUpsertStatement
	if strings.TrimSpace(statement) == "" {
		return fmt.Errorf("SQLUpsertStatement is empty because the model has no unique columns")
	}

	values, err := userSQLDriverValues(model)
	if err != nil {
		return err
	}
	userSQLTouchUpdatedAt(values)

	_, err = db.ExecContext(ctx, statement, values...)
	return err
}

// SQLDelete удаляет записи модели User по фильтрам.
func Delete(ctx context.Context, db Executor, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLDelete requires at least one filter")
	}

	where, args, err := userSQLBuildWhere(filters, 1)
	if err != nil {
		return err
	}

	query := "DELETE FROM " + userSQLTableName + where
	_, err = db.ExecContext(ctx, query, args...)
	return err
}

// SQLList возвращает список моделей User с пагинацией.
func List(ctx context.Context, db Executor, limit int, offset int) ([]modelpkg.User, error) {
	query := userSQLSelectStatement
	if orderBy := userSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}

	query, args := userSQLAppendPagination(query, nil, limit, offset)

	return userSQLQueryMany(ctx, db, query, args...)
}

// SQLSearch ищет модели User по текстовому запросу.
func Search(ctx context.Context, db Executor, term string, limit int, offset int) ([]modelpkg.User, error) {
	trimmed := strings.TrimSpace(term)
	if trimmed == "" || len(userSQLSearchColumns) == 0 {
		return List(ctx, db, limit, offset)
	}

	pattern := "%" + trimmed + "%"
	parts := make([]string, 0, len(userSQLSearchColumns))
	args := make([]any, 0, len(userSQLSearchColumns)+2)
	for _, column := range userSQLSearchColumns {
		args = append(args, pattern)
		parts = append(parts, fmt.Sprintf("LOWER(%s) LIKE LOWER(%s)", column, userSQLPlaceholder(column, len(args))))
	}

	query := userSQLSelectStatement + " WHERE (" + strings.Join(parts, " OR ") + ")"
	if orderBy := userSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}
	query, args = userSQLAppendPagination(query, args, limit, offset)

	return userSQLQueryMany(ctx, db, query, args...)
}

// Store хранит SQL executor для операций модели User.
type Store struct {
	db Executor
}

// NewStore создает SQL store для модели User.
func NewStore(db Executor) *Store {
	return &Store{db: db}
}

func (store *Store) executor() (Executor, error) {
	if store == nil || store.db == nil {
		return nil, fmt.Errorf("sql store executor is nil")
	}
	return store.db, nil
}

func (store *Store) DB() Executor {
	if store == nil {
		return nil
	}
	return store.db
}

func (store *Store) WithExecutor(db Executor) *Store {
	return NewStore(db)
}

func (store *Store) Init(ctx context.Context) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Init(ctx, db)
}

func (store *Store) Create(ctx context.Context, model modelpkg.User) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Create(ctx, db, model)
}

func (store *Store) Get(ctx context.Context, filters map[string]any) (modelpkg.User, error) {
	db, err := store.executor()
	if err != nil {
		return modelpkg.User{}, err
	}
	return Get(ctx, db, filters)
}

func (store *Store) Update(ctx context.Context, model modelpkg.User, filters map[string]any) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Update(ctx, db, model, filters)
}

func (store *Store) Delete(ctx context.Context, filters map[string]any) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Delete(ctx, db, filters)
}

func (store *Store) List(ctx context.Context, limit int, offset int) ([]modelpkg.User, error) {
	db, err := store.executor()
	if err != nil {
		return nil, err
	}
	return List(ctx, db, limit, offset)
}

func (store *Store) Search(ctx context.Context, term string, limit int, offset int) ([]modelpkg.User, error) {
	db, err := store.executor()
	if err != nil {
		return nil, err
	}
	return Search(ctx, db, term, limit, offset)
}

func (store *Store) Upsert(ctx context.Context, model modelpkg.User) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Upsert(ctx, db, model)
}
