// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"fmt"
	modelpkg "m/src/user"
	"strings"
)

// sqlDriverValues подготавливает значения модели User для SQL-запросов.
func userSQLDriverValues(model modelpkg.User) ([]any, error) {
	values := make([]any, 0, len(userSQLColumnNames))
	values = append(values, model.Id)
	values = append(values, model.Name)
	values = append(values, model.Phone)
	return values, nil
}

// userSQLPlaceholder строит SQL placeholder для конкретной колонки.
func userSQLPlaceholder(columnName string, index int) string {
	column, ok := userSQLNormalizeColumnName(columnName)
	if !ok {
		return fmt.Sprintf("$%d", index)
	}
	switch column {
	default:
		return fmt.Sprintf("$%d", index)
	}
}

// userSQLNormalizeColumnName нормализует имя поля модели в имя SQL-колонки.
func userSQLNormalizeColumnName(name string) (string, bool) {
	switch strings.TrimSpace(name) {
	case "Id", "id":
		return "\"id\"", true
	case "Name", "name":
		return "\"name\"", true
	case "Phone", "phone":
		return "\"phone\"", true
	default:
		return "", false
	}
}

// userSQLNormalizeFilterValue приводит значение фильтра к SQL-совместимому виду.
func userSQLNormalizeFilterValue(columnName string, value any) (any, error) {
	column, ok := userSQLNormalizeColumnName(columnName)
	if !ok {
		return nil, fmt.Errorf("unknown sql filter column %q", columnName)
	}
	if value == nil {
		return nil, nil
	}
	switch column {
	default:
		return value, nil
	}
}

// sqlBuildUpdateAssignments подготавливает SET-часть UPDATE для модели User.
func userSQLBuildUpdateAssignments(model modelpkg.User, startIndex int) (string, []any, error) {
	values, err := userSQLDriverValues(model)
	if err != nil {
		return "", nil, err
	}
	userSQLTouchUpdatedAt(values)
	if len(userSQLUpdateColumnIndexes) == 0 {
		return "", nil, fmt.Errorf("model User has no mutable SQL columns")
	}

	columns := userSQLColumnNames
	parts := make([]string, 0, len(userSQLUpdateColumnIndexes))
	args := make([]any, 0, len(userSQLUpdateColumnIndexes))

	for _, index := range userSQLUpdateColumnIndexes {
		column := columns[index]
		parts = append(parts, fmt.Sprintf("%s = %s", column, userSQLPlaceholder(column, startIndex+len(args))))
		args = append(args, values[index])
	}

	return strings.Join(parts, ", "), args, nil
}

// sqlScan заполняет модель User данными из SQL scanner.
func userSQLScan(scanner interface{ Scan(dest ...any) error }, model *modelpkg.User) error {
	var idValue int64
	var nameValue string
	var phoneValue string
	if err := scanner.Scan(&idValue, &nameValue, &phoneValue); err != nil {
		return err
	}
	model.Id = int(idValue)
	model.Name = nameValue
	model.Phone = phoneValue
	return nil
}

func userSQLTouchUpdatedAt(values []any) {
	_ = values
}
