// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	stdsql "database/sql"
)

type Executor interface {
	ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *stdsql.Row
}

const TableName = "user"

const userSQLTableName = "\"user\""

type Column string

const (
	ColumnId    Column = "id"
	ColumnName  Column = "name"
	ColumnPhone Column = "phone"
)

func (column Column) String() string {
	return string(column)
}

func Where(column Column, value any) map[string]any {
	return map[string]any{string(column): value}
}

func And(filters ...map[string]any) map[string]any {
	result := make(map[string]any)
	for _, filter := range filters {
		for column, value := range filter {
			result[column] = value
		}
	}
	return result
}

var userSQLColumnNames = []string{"\"id\"", "\"name\"", "\"phone\""}

var userSQLSearchColumns = []string{"\"name\"", "\"phone\""}

const userSQLSelectStatement = "SELECT \"id\", \"name\", \"phone\" FROM \"user\""

const userSQLOrderByColumn = "\"id\""

var userSQLCreateStatements = []string{
	"CREATE TABLE IF NOT EXISTS \"user\" (\n    \"id\" BIGINT NOT NULL UNIQUE,\n    \"name\" TEXT NOT NULL,\n    \"phone\" TEXT NOT NULL\n);",
}

const userSQLInsertStatement = "INSERT INTO \"user\" (\"id\", \"name\", \"phone\") VALUES ($1, $2, $3);"

var userSQLUpdateColumnIndexes = []int{0, 1, 2}

const userSQLUpsertStatement = "INSERT INTO \"user\" (\"id\", \"name\", \"phone\") VALUES ($1, $2, $3) ON CONFLICT (\"id\") DO UPDATE SET \"name\" = EXCLUDED.\"name\", \"phone\" = EXCLUDED.\"phone\";"
